src/main/webapp/ui/src/eln/gallery/components/MainPanel.js, src/main/webapp/ui/src/eln/gallery/useGalleryActions.js, src/main/webapp/ui/src/eln/gallery/useGalleryListing.js
System folders that include the substring "SNIPPETS" are populated based on how the user has chosen to share their snippets, not by manually moving them around. As such, the drag-and-drop functionality on the new Gallery page should throw an error rather than attempt to move the snippets, as doing so will result in nothing being done but nonetheless the backend responding with a 200.
=> RSDEV-249 Prevent items from being drag-and-dropped into Snippets folders on new Gallery page

src/main/webapp/ui/src/accentedTheme.js, src/main/webapp/ui/src/eln/gallery/components/AppBar.js, src/main/webapp/ui/src/eln/gallery/index.js
This change makes the help button in the header of the new Gallery page open the Lighthouse-driven help popup that we use throughout the product.
My intention is that as more of the ELN is reactified this will become the standard way of accessing help as the current mechanism is inconsistent: the floating action button doesn't work on mobile and has to be hidden/moved when opening dialogs, and Inventory has a button in the sidebar which wont work on pages that don't need a sidebar.
https://github.com/rspace-os/rspace-web/assets/8805923/f21112de-098f-4ef0-9edd-57869c961961
Note that like in Inventory, the button is disabled until all of the third-party scripts have been loaded. Ordinarily, I don't like disabled buttons but the loading of this functionality seems to be very robust and …
=> RSDEV-243 Have help icon in top right corner open Lighthouse

src/main/webapp/ui/src/Inventory/Mixed/CreateDialog.js
This change adds a split option to the Sample create dialog, which when there is just one subsamples allows the user to quickly split that one subsample.
When there are multiple subsamples the split option is disabled, with an explanation of what to do instead.
=> RSDEV-261 Add split option to samples "Create" dialog when there is only one subsample

src/main/webapp/ui/src/Inventory/Sample/Fields/NumberOfSubSamples.js, src/main/webapp/ui/src/Inventory/Sample/Fields/Quantity.js, src/main/webapp/ui/src/Inventory/Sample/Fields/__tests__/Quantity.test.js, src/main/webapp/ui/src/Inventory/components/Inputs/FormField.js
This change modifies the form for creating samples, guiding the user through the instantiation of the subsamples to make it clearer when working with indivisible substances.
Currently, the form looks like this
and after this change is behaves like this
https://github.com/rspace-os/rspace-web/assets/8805923/379455b3-2230-4f92-a365-f4567fc89e6d
The user is guided through the two options which either creates one subsample (which should largely be transparent), or allows the user to specify multiple subsamples. The quantity field then adjusts accordingly.
=> RSDEV-81 Type radio field for samples to guide subsample creation

src/main/java/com/researchspace/service/NfsManager.java, src/main/java/com/researchspace/webapp/controller/IgnoreInServiceLoggerAspct.java, src/main/java/com/researchspace/webapp/controller/ServiceLoggerAspct.java
This PR adds `IgnoreInServiceLoggerAspct` annotation, which works similarly to `IgnoreInLoggingInterceptor` annotation, i.e. can be used for marking method for which connected aspect (`ServiceLoggerAspct`) shouldn't print parameters passed to the method.
This should solve [issue#42](https://github.com/rspace-os/rspace-web/issues/42) and also internal issue RSPAC-2017.
=> add IgnoreInServiceLoggerAspct annotation that can stop logging parameter of long-execution call

src/main/webapp/ui/src/Toolbar/Gallery/IrodsWrapper.js, src/main/webapp/ui/src/Toolbar/Gallery/MoveToIrods.js, src/main/webapp/ui/src/Toolbar/Gallery/Toolbar.js, src/main/webapp/ui/src/accentedTheme.js, src/main/webapp/ui/src/components/AccessibilityTips.js, src/main/webapp/ui/src/eln-dmp-integration/Argos/ArgosNewMenuItem.js, src/main/webapp/ui/src/eln-dmp-integration/DMPOnline/DMPOnlineNewMenuItem.js, src/main/webapp/ui/src/eln-dmp-integration/DMPTool/DMPToolNewMenuItem.js, src/main/webapp/ui/src/eln/gallery/common.js, src/main/webapp/ui/src/eln/gallery/components/ActionsMenu.js, src/main/webapp/ui/src/eln/gallery/components/AppBar.js, src/main/webapp/ui/src/eln/gallery/components/IrodsLogo.svg, src/main/webapp/ui/src/eln/gallery/components/MainPanel.js, src/main/webapp/ui/src/eln/gallery/components/MoveDialog.js, src/main/webapp/ui/src/eln/gallery/components/MoveToIrods.js, src/main/webapp/ui/src/eln/gallery/components/NewMenuItem.js, src/main/webapp/ui/src/eln/gallery/components/PlaceholderLabel.js, src/main/webapp/ui/src/eln/gallery/components/Sidebar.js, src/main/webapp/ui/src/eln/gallery/components/TreeView.js, src/main/webapp/ui/src/eln/gallery/components/useIrods.js, src/main/webapp/ui/src/eln/gallery/index.js, src/main/webapp/ui/src/eln/gallery/useGalleryActions.js, src/main/webapp/ui/src/eln/gallery/useGalleryListing.js, src/main/webapp/ui/src/eln/gallery/useGallerySelection.js, src/main/webapp/ui/src/util/set.js, src/main/webapp/ui/src/util/table.js
This change adds a new menu to the new gallery page, which provides the user with various actions that they can perform on the selected files. It includes all of the actions from the current gallery's menubar, but not all are yet implemented as some require backend development work and others -- such as the export flow -- require their own substantial rework that is best tackled separately.
This change also includes
- a different theme colour so that the UI is more distinctive to the iRODS branding
- an additional accessibility tip, describing the support for up to 200% zoom
- on mobile and small windows, the sidebar now full closes and opens above all other content to prevent the page for overflow horizontally.
=> RSDEV-264 Add an actions menu to the new gallery

src/main/java/com/researchspace/webapp/controller/MessageAndRequestController.java, src/main/webapp/scripts/pages/workspace/editor/tinymce5_configuration.js, src/main/webapp/styles/pages/workspace/workspace.css
This change displays all users in a scrolling list when the user enter the "@" key in a rich text field in the ELN, as opposed to the current functionality which arbitrarily limits the list to 10 users.
=> RSDEV-225 Show all users in mentions list

src/main/webapp/ui/src/Inventory/Sample/Content/SubsampleDetails.js, src/main/webapp/ui/src/Inventory/Sample/Content/SubsampleListing.js, src/main/webapp/ui/src/Inventory/Sample/Form.js, src/main/webapp/ui/src/Inventory/Search/ResultsTable.js, src/main/webapp/ui/src/Inventory/Search/components/ResultRow.js, src/main/webapp/ui/src/Inventory/Subsample/Fields/Notes/NewNote.js, src/main/webapp/ui/src/Inventory/Subsample/Fields/Notes/Notes.js, src/main/webapp/ui/src/Inventory/Subsample/Form.js, src/main/webapp/ui/src/Inventory/components/DetailedListing/Card.js, src/main/webapp/ui/src/stores/definitions/Search.js, src/main/webapp/ui/src/stores/models/Fetcher/CacheFetcher.js, src/main/webapp/ui/src/stores/models/Fetcher/CoreFetcher.js, src/main/webapp/ui/src/stores/models/Fetcher/DynamicFetcher.js, src/main/webapp/ui/src/stores/models/Search.js, src/main/webapp/ui/src/stores/models/__tests__/Search/setBench.test.js, src/main/webapp/ui/src/stores/models/__tests__/Search/setDeletedItems.test.js, src/main/webapp/ui/src/stores/models/__tests__/Search/setOwner.test.js, src/main/webapp/ui/src/stores/models/__tests__/Search/setPageSize.test.js, src/main/webapp/ui/src/stores/models/__tests__/Search/setTypeFilter.test.js
This change adds a new section to the sample page, showing some details of each subsample. This is to make it easier to browse those details without having to click around each subsample page, particularly useful when samples regularly only have one subsample.
This new panel appears below the subsample listing table, with the subsample theme colours to distinguish it from the sample itself. The user can browse back and forward between the subsample with the arrow buttons, or just to a specific subsample by tapping a row in the table (viewing the subsample's own page is now reachable by tapping the Global ID link or the link at the end of the new panel). The location, quantity, and notes fields are shown; fields that are specific to the subsample and detail what is unique about this …
=> RSDEV-260 Add subsamples details section to sample page

src/main/java/com/researchspace/webapp/controller/DeploymentPropertiesController.java, src/main/webapp/ui/src/eln/sysadmin/users/index.js, src/main/webapp/ui/src/eln/sysadmin/users/useUserListing.js
The delete user sysadmin menu item is now disabled if the deployment property is set, with an explanation as such.
Furthermore, I've fixed the error handling for the network request to ensure that any other reason for the deletion operation failing is made apparent.
=> Issue 46 sysadmin delete button

src/main/webapp/ui/src/Inventory/Subsample/Fields/Quantity.js, src/main/webapp/ui/src/Inventory/components/Fields/Sample.js
This change adds an additional label on the subsample form informing the user of how many siblings the subsample has.
Currently, the subsamples quantity field provides a link to the search for all of the parent sample's subsamples, with a link text that specifies the number of subsamples minus one -- the number of siblings the subsample has. Given that the quantity field is in the details section, it may appear below the fold when the vertical dimension of the viewport is low or it may not be visible due to the details section being collapsed.
This change duplicates this label by adding it to the overview section's parent sample field also, where it is more likely to be seen at first glance.
=> RSDEV-279 Additional subsample count label

src/main/webapp/WEB-INF/decorators.xml, src/main/webapp/WEB-INF/urlrewrite.xml, src/main/webapp/ui/flow-typed/mui.js, src/main/webapp/ui/src/accentedTheme.js, src/main/webapp/ui/src/components/EventBoundary.js, src/main/webapp/ui/src/components/useOneDimensionalRovingTabIndex.js, src/main/webapp/ui/src/eln/gallery/common.js, src/main/webapp/ui/src/eln/gallery/components/ActionsMenu.js, src/main/webapp/ui/src/eln/gallery/components/MainPanel.js, src/main/webapp/ui/src/eln/gallery/components/Sidebar.js, src/main/webapp/ui/src/eln/gallery/components/TreeView.js, src/main/webapp/ui/src/eln/gallery/index.js, src/main/webapp/ui/src/eln/gallery/useGalleryListing.js, src/main/webapp/ui/src/eln/gallery/useGallerySelection.js
This change alters how the breadcrumbs and other buttons and menus at the top of the new gallery page are rendered.
The breadcrumbs, a series of links allowing the users to navigate back up the folder hierarchy, is now rendered within a horizontally scrolling box. When tapped, it transforms into a read-only text field that allows users to select and copy the path, which would not otherwise be possible. Keyboard controls are fully supported, with a roving tab index employed for moving the focus between the links and tab correctly triggering the read-only text field. Being able to drag-and-drop onto the breadcrumbs is retained, with the animated added whilst dragging to make it clear which UI elements are dropzones. Note the blue outline:
The remaining buttons and menus -- actions, sorting, …
=> RSDEV-277 Improve breadcrumbs on new Gallery page

src/main/webapp/ui/src/Inventory/Subsample/Fields/Notes/NoteItem.js, src/main/webapp/ui/src/Inventory/Subsample/Fields/Notes/Notes.js, src/main/webapp/ui/src/Inventory/Subsample/Fields/Notes/NotesList.js
If subsamples have lots of notes then it could make the UI quite cumbersome, especially where the subsample notes are now shown on the sample page they are no longer at the very foot of the page as they are on the subsample page.
This change hides all but the two most recent notes by default, with the rest hidden behind a "Show more" button. The new note field is placed at the top of the list, where it appears before the most recent note and is readily available even when the list of notes is long.
This change also improves the aesthetics of the notes somewhat, utilising the theme colour of the subsamples to make it clear that the notes are associated with the physical quantity of the sample, and not the grouping that forms the whole sample.
=> RSDEV-282 By default, hide all but the most recent two notes on subsamples

src/main/webapp/ui/src/tinyMCE/pyrat/Pyrat.js
This change reduces to the font size of the generated PyRAT table that is inserted into the rich text fields of documents by the PyRAT integration. This is done to reduced the probability of horizontal scrolling being required most of the time.
This image shows the new font-size at the top and the old size just below it.
=> RSDEV-302 Shrink size of generated PyRAT table

src/main/java/com/researchspace/api/v1/UserDetailsSysAdminApi.java, src/main/java/com/researchspace/api/v1/controller/UserDetailsSysAdminApiController.java, src/main/java/com/researchspace/webapp/controller/UserProfileController.java, src/main/resources/deployments/defaultDeployment.properties, src/main/resources/deployments/dev/deployment.properties, src/main/webapp/WEB-INF/pages/userform.jsp, src/main/webapp/scripts/pages/userform.js, src/test/java/com/researchspace/webapp/controller/UserProfileControllerMVCIT.java
This PR consists of multiple changes that should make retrieval of API key more secure and traceable.
The changes in behaviour:
- for user who generated API key the value of their key is no longer sent to front-end whenever 'My Profile' page is displayed, but only after user explicitly clicks on 'Show Key' link
- when System Admin user 'operates as' they can no longer see user's API key ('Show Key' returns an error); System Admin can still generate new API key or revoke the old one, as there may be valid reasons for these actions (similarly how we do allow System Admin to reset user's password)
- the `/apiKeyInfo/all` endpoint within `UserDetailsSysAdminApi` is now only available when deployment property `sysadmin.apikey.access` is set to `true` (it's `false` by default)
=> issue-73: reworking API key display logic and ways for sysadmin to access it

src/main/webapp/ui/src/tinyMCE/pyrat/Pyrat.js
This change adds a row to the top of the table that is inserted into the rich text fields of documents by the PyRAT integrations. This row includes a link back to the PyRAT server and the date of when the table was generated.
=> RSDEV-301 Add link to PyRAT server at top of generated table

src/main/webapp/ui/src/Inventory/Sample/Content/SubsampleDetails.js
When the subsample search within the sample form changes (e.g. the user searches for a particular subsample using the query string field), the subsample details panel should update so that we're not showing the details of subsample that are no longer in the table.
This is somewhat complicated by the next and previous buttons below the details panel as they manipulated the search when the currently shown subsample is up against a page boundary. The finer details of this complication are in the code comments.
=> RSDEV-304 Update subsample details when search changes

src/main/webapp/ui/flow-typed/mui.js, src/main/webapp/ui/src/eln-dmp-integration/Argos/DMPDialog.js, src/main/webapp/ui/src/eln-dmp-integration/DMPTool/DMPDialog.js, src/main/webapp/ui/src/eln-dmp-integration/DMPTool/ScopeField.js, src/main/webapp/ui/src/eln-dmp-integration/DMPTool/__tests__/DMPDialog.test.js, src/main/webapp/ui/src/eln-dmp-integration/DMPTool/__tests__/DMPToolMenuItem.test.js, src/main/webapp/ui/src/util/table.js
This means the DMPTool dialog for importing DMPs into the Gallery has consistent styling with the new Gallery, utilising an accented theme to mimic the DMPTool branding. Moreover, it supports the high contrast mode that comes with the theme. The dialog also now uses MUI's DataGrid, allowing the user to choose additional columns of data. This change applies to both the existing and new gallery.
Current gallery before
Current gallery after
New gallery before
New gallery after
This change also includes keyboard controls for selecting a row of the table in the Argos dialog as that was not included in its recent change.
=> RSDEV-120  Migrate DMPTool dialog to accented theme

src/main/webapp/ui/src/Export/ExportDialog.js, src/main/webapp/ui/src/Export/ExportModal.js, src/main/webapp/ui/src/Export/FormatChoice.js, src/main/webapp/ui/src/Export/__tests__/ExportDialog.test.js, src/main/webapp/ui/src/Export/__tests__/FormatChoice.test.js, src/main/webapp/ui/src/eln/gallery/components/ActionsMenu.js
This change makes a few stylistic changes to the export dialog to make it more consistent with the rest of the product, including
- Replacing the 'X' in the top right corner, with a 'Cancel' button at the bottom
- Make the dialog fullscreen on mobile devices
- Arrange the initial radio buttons with a short label and a smaller explanation below, rather than all on the same line.
This change also makes the export dialog work on the new gallery
=> RSDEV-270 Some improvements to the export dialog

DevDocs/DeveloperNotes/GettingStarted/GettingStarted.md
update docs explaining additional deployment param required to use a different database than the standard rspace
=> [#63] specify a different database using deployment properties

src/main/webapp/ui/src/components/Alerts/SnackbarContentWrapper.js, src/main/webapp/ui/src/stores/models/Search.js
When deleting a sample, if some of the subsamples are in containers then the user is prevented from being able to delete the sample as it is likely that some of the substance is still in use/in freezers/etc. However, in the case where a sample only ever has one subsample, or there happens to only be one subsample left, it would be very useful to be able to delete the sample and subsample both in one operation. Furthermore, there may be edge cases where it is desirable to delete all of the subsamples of a sample in a storage and the system should be flexible enough to support that it even if its is an unusual request.
As such, this change adds a button to the error toast that explains that some of the subsamples are still in containers that allows the user to force the deletion of all of …
=> RSDEV-257 Add "Move all to trash" button to error toast when deleting samples

src/main/webapp/ui/src/Inventory/components/Fields/Identifiers/GeoLocationField.js, src/main/webapp/ui/src/Inventory/components/Fields/Identifiers/Identifiers.js, src/main/webapp/ui/src/Inventory/components/Fields/Identifiers/MapViewer.js, src/main/webapp/ui/src/Inventory/components/Fields/Identifiers/MultipleInputHandler.js, src/main/webapp/ui/src/Inventory/components/Fields/Identifiers/PolygonCard.js, src/main/webapp/ui/src/Inventory/components/Fields/Identifiers/PublicPreviewDialog.js, src/main/webapp/ui/src/Inventory/components/Fields/Identifiers/PublishButton.js, src/main/webapp/ui/src/Inventory/components/Fields/Identifiers/__tests__/mocking.js, src/main/webapp/ui/src/components/PublicPages/IdentifierPublicPage.js, src/main/webapp/ui/src/stores/definitions/Factory.js, src/main/webapp/ui/src/stores/definitions/GeoLocation.js, src/main/webapp/ui/src/stores/definitions/Identifier.js, src/main/webapp/ui/src/stores/definitions/__tests__/Factory/mocking.js, src/main/webapp/ui/src/stores/models/Factory/AlwaysNewFactory.js, src/main/webapp/ui/src/stores/models/GeoLocationModel.js, src/main/webapp/ui/src/stores/models/IdentifierModel.js, src/main/webapp/ui/src/stores/models/Result.js, src/main/webapp/ui/src/util/ArrayUtils.js
The first and last points of a GeoLocation polygon must be the same to enclose a region. This invariant was not sufficiently being enforced and so this change defines a new class and accompanying interface to ensure all code that creates and modifies GeoLocation polygons enforces this invariant.
Further changes were necessary because the GeoLocation classes could not be used on the public page due to transitive dependencies on AuthStore, which this change fixes with a little dependency injection. This makes `publicData` unnecessary.
=> PRT-794 Define GeoLocationPolygon class to enforce bounding region

src/main/webapp/ui/.dependency-cruiser.js, src/main/webapp/ui/src/components/PublicPages/IdentifierPublicPage.js, src/main/webapp/ui/src/components/PublicPages/README.md, src/main/webapp/ui/src/stores/models/GeoLocationModel.js, src/main/webapp/ui/src/stores/models/IdentifierModel.js
After dealing with a bug about how public pages must not import the global stores (commit 21e8f97), I have expanded on the in-code documentation and written a guide on debugging such issues with the addition of a dependency-cruiser rule to aid such debugging.
=> Documentation about debugging public pages

src/main/webapp/ui/src/Inventory/Search/SearchRouter.js, src/main/webapp/ui/src/Inventory/components/Stepper/StepperPanelHeader.js, src/main/webapp/ui/src/Inventory/components/Stepper/SynchroniseFormSections.js, src/main/webapp/ui/src/eln/gallery/components/MainPanel.js, src/main/webapp/ui/src/eln/gallery/index.js, src/main/webapp/ui/src/util/useUiPreference.js
There are various small bits of the UI that would be good to persist across user sessions: sort ordering, views, draft text.
This change adds a custom react hook for using bits of persisted state in the same way that React.useState is used. The state is stored with its timestamp so that in future we could implement a retention policy/flush the oldest state when necessary. Finally, this change uses this new hook to provide persistence for:
* New Gallery's sorting
* New Gallery's view
* Inventory's form sections
=> RSDEV-325 Use UI preferences to persist UI state in React-land

src/main/webapp/ui/src/eln/gallery/components/ActionsMenu.js, src/main/webapp/ui/src/eln/gallery/components/MainPanel.js, src/main/webapp/ui/src/eln/gallery/useGalleryActions.js, src/main/webapp/ui/src/eln/gallery/useGalleryListing.js, src/main/webapp/ui/src/util/result.js
On the current gallery, this button sits on the info panel but to streamline the info panel and place all buttons that perform actions in one place this is being moved to the actions menu -- the equivalent of the menu bar -- on the new gallery page.
=> RSDEV-286 On new gallery, move "upload new version" to actions menu

src/main/webapp/ui/.dependency-cruiser.js
This dependency cruiser rule encodes a whitelist of strings of which at least one must appear in the license string of every third-party library we install from npm. As such, by running dependency cruiser, any violations will be reported.
=> RSDEV-196 Have dependency cruiser check for incompatible licenses

src/main/java/com/researchspace/webapp/controller/SignupController.java, src/main/java/com/researchspace/webapp/filter/SAMLRemoteUserPolicy.java, src/main/resources/deployments/defaultDeployment.properties, src/test/java/com/researchspace/api/v1/controller/SysadminUsersAPIController2MVCIT.java, src/test/java/com/researchspace/api/v1/controller/SysadminUsersAPIControllerMVCIT.java, src/test/java/com/researchspace/webapp/controller/SignupControllerTest.java
adds deployment property that enables re-coding of first name and last name coming from SAML response from iso-8859-1 to utf8 response
=> RSPAC-2209: option to utf8-recode first name/last name coming from SAML response

src/main/webapp/ui/src/Inventory/components/Fields/Attachments/AttachmentTableRow.js, src/main/webapp/ui/src/components/Inputs/__tests__/AttachmentField.test.js, src/main/webapp/ui/src/stores/definitions/Attachment.js, src/main/webapp/ui/src/stores/definitions/__tests__/Attachment/mocking.js, src/main/webapp/ui/src/stores/models/AttachmentModel.js, src/main/webapp/ui/src/stores/models/FieldModel.js, src/main/webapp/ui/src/stores/models/Result.js, src/main/webapp/ui/src/stores/models/SampleModel.js, src/main/webapp/ui/src/stores/models/__tests__/AttachmentModel/getFile.test.js
This is a completely non-functional change that refactors AttachmentModel into two separate classes to remove the conditional logic that toggles the behaviour based on whether the attachment has been persisted in the database or not.
This is in anticipation of the change to allow attachments to be chosen from the Gallery, which further adds permutations of the state that attachments can be in and thus more conditional logic.
=> RSDEV-174 Refactor AttachmentModel in anticipation of attaching Gallery files

src/main/java/com/researchspace/dao/FileMetadataDao.java, src/main/java/com/researchspace/dao/SampleDao.java, src/main/java/com/researchspace/dao/hibernate/FileMetadataHibernate.java, src/main/java/com/researchspace/dao/hibernate/SampleDaoHibernateImpl.java, src/main/java/com/researchspace/service/FileStoreMetaManager.java, src/main/java/com/researchspace/service/impl/FileStoreMetaManagerImpl.java, src/main/java/com/researchspace/service/inventory/InventoryRecordRetriever.java, src/main/java/com/researchspace/service/inventory/impl/InventoryFileApiManagerImpl.java
As suggested and as a performance fix, check first if the user owns any record which references the image file being retrieved. 
If not split the next check for user having permissions to view (when they aren't owner) up by `InventoryRecord` type, starting with sample template which is the most likely way a user will access a file they do not own.
=> Improve image retrieval performance 

src/main/webapp/ui/src/Inventory/Container/NewRecordForm.js, src/main/webapp/ui/src/Inventory/Sample/NewRecordForm.js
When attaching a file to an Inventory record, there is a button to use that file as the preview image for the record. This button, however, was not working when creating new records as `fieldOwner` was not being passed to `AttachmentsField` in the two NewRecordForms that support Attachments (subsamples have no NewRecordForm and templates do not support attachments)
=> RSDEV-364 Fix setting attachments on new record as the preview image

src/main/webapp/ui/src/my-rspace/directory/groups/UserList.js, src/main/webapp/ui/src/system-groups/UserList.js, src/main/webapp/ui/src/util/StringUtils.js, src/main/webapp/ui/src/util/__tests__/StringUtils/stripDiacritics.test.js
This changes adds a little logic to the two places where searching for people's names is performed in the frontend code, allowing for a searcher to provide a query string that does not contain diacritics and still get results for names that do not contain such marks.
=> RSDEV-357 Allow searching for names that contain diacritics by using characters that don't have them

src/main/webapp/scripts/tags/createFromTemplateDlg.js
The dialog is broken up into three separate forms:
1. One for filtering the template picker
2. One for typing in a name
3. One for actually making the network call
This change wires up the submit event of the second to the third so that pressing the enter key after typing in a name for the template the network call is made and the user is redirected to their new document, just as if they had tapped the 'Create' button
=> RSDEV-375 Submit ELN's "Create from Template" dialog with enter

DevDocs/public/RSpaceConfiguration.md, src/main/java/com/axiope/service/cfg/ProductionConfig.java, src/main/java/com/researchspace/auth/MaintenanceLoginAuthorizer.java, src/main/java/com/researchspace/properties/IPropertyHolder.java, src/main/java/com/researchspace/properties/PropertyHolder.java, src/main/java/com/researchspace/webapp/controller/SignupController.java, src/main/java/com/researchspace/webapp/filter/AbstractSsoRemoteUserPolicy.java, src/main/java/com/researchspace/webapp/filter/EASERemoteUserPolicy.java, src/main/java/com/researchspace/webapp/filter/MockRemoteUserPolicy.java, src/main/java/com/researchspace/webapp/filter/OpenIdRemoteUserPolicy.java, src/main/java/com/researchspace/webapp/filter/RemoteUserRetrievalPolicy.java, src/main/java/com/researchspace/webapp/filter/SAMLRemoteUserPolicy.java, src/main/java/com/researchspace/webapp/filter/SSOShiroFormAuthFilterExt.java, src/main/resources/bundles/workspace/workspace.properties, src/main/resources/deployments/defaultDeployment.properties, src/main/resources/deployments/dev/deployment.properties, src/main/webapp/WEB-INF/dispatcher-servlet.xml, src/main/webapp/WEB-INF/pages/public/ssologout.jsp, src/test/java/com/researchspace/webapp/controller/SignupControllerTest.java, src/test/java/com/researchspace/webapp/filter/OpenIdRemoteUserPolicyTest.java, src/test/java/com/researchspace/webapp/filter/SAMLRemoteUserPolicyTest.java, src/test/java/com/researchspace/webapp/filter/SSOShiroFormAuthFilterTest.java
This PR implements [RSDEV-284](https://researchspace.atlassian.net/browse/RSDEV-284) ticket, and it can be functionally tested at https://openid-connect.researchspace.com (maybe contact me/Ramon before trying, as we're testing various configurations right now).
Code-wise the new functionality is implemented through new `OpenIdRemoteUserPolicy.java` class, but I also did some refactoring around classes implementing `RemoteUserRetrievalPolicy`, as the code was quite tied to SAML (shibboleth) integration, which was the main SSO system we've been using until now.
=> RSDEV-284: support for OpenID Connect as SSO provider

src/main/webapp/scripts/pages/system/settings_mod.js
Currently unused so we're removing it from the UI so as not to confuse sysadmins but leaving the rest of the code in place in case we want to starting using again.
=> RSDEV-358 Remove onboarding sysadmin config option

src/main/webapp/ui/src/Export/ExportDialog.js, src/main/webapp/ui/src/Export/__tests__/ExportDialog.test.js
Commit c65e40c6c9 broke the logic that deserialises the API response for getting the list of tags set on a list of documents, which is used to suggest the tags that should be included in an export to the repositories. As such, the tags were silently not being included.
=> PRT-815 Fix the autosuggesting of tags when exporting documents

Jenkinsfile
`FORCE_COLOR=false` [is necessary for jest itself](https://jestjs.io/docs/cli#--colors).
> Alternatively you can set the environment variable FORCE_COLOR=true to forcefully enable or FORCE_COLOR=false to disable colorized output. The use of FORCE_COLOR overrides all other color support checks.
`COLORS=false` [is necessary for the DOM printing by testing-library to not include colours](https://testing-library.com/docs/dom-testing-library/api-debugging/#prettydom:~:text=Note%3A%20The%20output,on.%20For%20example%3A).
> Note: The output of the DOM is colorized by default if your tests are running in a node environment. However, you may sometimes want to turn off colors, such as in cases where the output is written to a log file for debugging purposes. You can use the environment variable …
=> Jenkins: Prevent ansi-escape codes from being logged by jest

src/main/webapp/ui/src/eln/gallery/components/InfoPanel.js, src/main/webapp/ui/src/eln/gallery/components/MainPanel.js, src/main/webapp/ui/src/eln/gallery/primaryActionHooks.js, src/main/webapp/ui/src/eln/gallery/useGalleryListing.js
Double clicking the file card and the button in the info panel should have the same behaviour, in that given a file of a specific type and a set of configured integrations (office online, collabora, aspose) the two UI elements should present the user with the same means of previewing the file.
To achieve this, this change adds a new custom hook that wraps all of the previously defined hooks for previewing gallery files.
=> RSDEV-381 Define usePrimaryAction hook to ensure UI consistency

src/main/webapp/ui/src/eln/gallery/components/ActionsMenu.js
Because the whole actions menu is disabled when there is nothing selected, there is no need for each menu item to check that the selection is not empty.
=> RSDEV-381 Remove check for empty selection for each menu item in actions menu

src/main/java/com/researchspace/ldap/impl/LdapSearchCmdLineExecutor.java, src/test/java/com/researchspace/ldap/impl/LdapSearchCmdLineExecutorTest.java, src/test/java/com/researchspace/webapp/filter/SSOShiroFormAuthFilterTest.java
In previous versions of Ubuntu the ldapsearch command required the -h flag to specify the host. However on ubuntu 22.04 and newer the -h flag breaks the command and you can just specify the IP with the -h flag and it works.
As a result, this breaks RSpace from being able to be setup with LDAP SSO when running on Ubuntu 22.04
I've edited the Java code to remove the -h flag when it calls the ldapsearch command.
This would fix LDAP for ubuntu 22.04 servers. 
Just creating this as a draft request at the moment, because I still need to check some things over from the DevOps side. When I have I'll change to a full pull request
=> Fix for ldapsearch command (which RSpace calls on LDAP setup) no longer working on ubuntu22.04 and newer

src/main/webapp/ui/src/Export/FormatChoice.js
Quick fix for an export to DCD issue found by selenium test, `repoCfg` was no longer initialized correctly as the label has changed, and the code was conditional on the label text.
=> RSDEV-346: fix repoCfg object passed on DCD export

src/main/webapp/ui/src/Export/FormatChoice.js
Most importantly this replaces the use of `displayName` with `repoName`, which is what the logic of the code should exclusively rely on. Nobody would expect that changing the `displayName` would have a functional change to the logic.
Secondly, this change makes is explicit that it is dataverse that is doing the exceptional thing by supporting multiple destinations and not all of the other repository services by inverting the conditional logic and adding explanatory comments.
=> Refactor setup of repoCfg

src/main/webapp/ui/src/components/ImagePreview.js, src/main/webapp/ui/src/eln/gallery/components/ActionsMenu.js, src/main/webapp/ui/src/eln/gallery/components/CallableImagePreview.js, src/main/webapp/ui/src/eln/gallery/components/InfoPanel.js, src/main/webapp/ui/src/eln/gallery/components/MainPanel.js, src/main/webapp/ui/src/eln/gallery/primaryActionHooks.js
When the user previews an image in the new gallery, the lightbox preview modal now shows the filename and description just like the old gallery
=> RSDEV-390 Show file name and description in image preview

src/main/java/com/researchspace/export/pdf/ExportToFileConfig.java, src/main/java/com/researchspace/export/pdf/PdfHtmlGenerator.java, src/main/java/com/researchspace/webapp/controller/GalleryController.java, src/main/resources/velocityTemplates/pdf/runningPageElems.vm, src/main/resources/velocityTemplates/pdf/styles.vm, src/main/webapp/scripts/tags/exportOtherDialogs.js, src/main/webapp/ui/src/Export/ExportDialog.js, src/main/webapp/ui/src/Export/PdfExport.js, src/main/webapp/ui/src/Export/__tests__/PdfExport.test.js, src/main/webapp/ui/src/eln/sysadmin/users/__tests__/pdfConfig.json, src/test/java/com/researchspace/export/pdf/HTMLStringGeneratorTest.java, src/test/java/com/researchspace/export/pdf/PdfHtmlGeneratorTest.java, src/test/java/com/researchspace/export/pdf/PdfProcessorTest.java, src/test/java/com/researchspace/service/PdfExportManagerTestIT.java
Turns out that introducing a new pdf-printing library (`flying-saucer-pdf`) caused a problem with exporting some ELN documents to PDF. The problem was caused by & (ampersand) character that RSpace may try to put into PDF page header (or footer) as a part of document name, or (less likely) as a part of full name of the exporting user. Attempt to export a document that has `&` in the name was resulting in an error like:
```
Can't load the XML resource (using TrAX transformer). org.xml.sax.SAXParseException; lineNumber: 19; 
columnNumber: 67; The reference to entity "in..." must end with the ';' delimiter..
```
After investigating, it seems that `flying-saucer-pdf` has a problem with interpreting html entities/chars passed through CSS 'content' attribute, which was how the header/footer …
=> RSDEV-411: a few fixes for pdf export, most importantly allow docs to have & (ampersand) in the name

src/main/java/com/researchspace/api/v1/service/impl/ExportTasklet.java, src/main/java/com/researchspace/service/archive/ExportImport.java, src/main/java/com/researchspace/service/impl/ExportImportImpl.java, src/main/java/com/researchspace/service/impl/PdfWordExportManagerImpl.java, src/main/java/com/researchspace/service/impl/PostRecordSigningExportHash.java, src/main/java/com/researchspace/webapp/controller/ExportController.java, src/main/java/com/researchspace/webapp/controller/UserExportHandler.java, src/main/resources/bundles/workspace/workspace.properties, src/test/java/com/researchspace/service/AutoshareManagerIT.java, src/test/java/com/researchspace/service/ExportImportManagerTestIT.java, src/test/java/com/researchspace/service/PdfExportManagerTestIT.java, src/test/java/com/researchspace/service/impl/PostRecordSigningExportHashTest.java, src/test/java/com/researchspace/webapp/controller/ExportControllerTest.java
In current codebase the PDF export fails for documents that have html entity hash code in their name (e.g. a doc named `test &#x3 doc`), but such error doesn't produce any notification, just bumps the notification count.
The main change of this PR is that async PDF exports now calls `postArchiveExportFailure()` in `catch` blocks on `ExportImportImpl` class level, which is the same pattern as used in async archive exports, and that pattern does result in error notification delivered to the user. The call to produce error notification in `PdfWordExportManagerImpl.processDocsForDocExport()`, which was resulting only in bumped notification count, is removed.
As a bit of refactoring, I also renamed most of the methods in `ExportImport` interface so they follow the same naming pattern. 
Compare …
=> RSDEV-418: more robust notifications for pdf export errors

src/main/java/com/researchspace/export/pdf/PdfHtmlGenerator.java, src/test/java/com/researchspace/export/pdf/PdfHtmlGeneratorTest.java, src/test/java/com/researchspace/service/PdfExportManagerTestIT.java
When exporting documents to PDF we convert them to xhtml representation, which is one expected by itext/flying-saucer. The content taken from document's rich text fields can be directly mapped, as it is already in html, but other data that is put into pdf, i.e. document's name/owner/exporting user's names, is not expected to be html-encoded. 
This PR escapes that other content for html output, so the random html-like char sequence occurring e.g. in document name, will not be treated by PDF lib as a request to print an html entity.
=> RSDEV-411: fix pdf exporting for documents with html hash-entity char sequence (&#) in name

src/main/webapp/ui/.dependency-cruiser.js, src/main/webapp/ui/package-lock.json, src/main/webapp/ui/package.json, src/main/webapp/ui/src/Inventory/Container/BatchForm.js, src/main/webapp/ui/src/Inventory/Container/Fields/LocationsImageField.js, src/main/webapp/ui/src/Inventory/Container/Form.js, src/main/webapp/ui/src/Inventory/Container/NewRecordForm.js, src/main/webapp/ui/src/Inventory/Mixed/BatchForm.js, src/main/webapp/ui/src/Inventory/Sample/BatchForm.js, src/main/webapp/ui/src/Inventory/Sample/Content/SubsampleDetails.js, src/main/webapp/ui/src/Inventory/Sample/Form.js, src/main/webapp/ui/src/Inventory/Sample/NewRecordForm.js, src/main/webapp/ui/src/Inventory/Subsample/BatchForm.js, src/main/webapp/ui/src/Inventory/Subsample/Form.js, src/main/webapp/ui/src/Inventory/Template/Form.js, src/main/webapp/ui/src/Inventory/Template/NewRecordForm.js, src/main/webapp/ui/src/Inventory/components/Fields/Image.js, src/main/webapp/ui/src/components/ImageEditingDialog.js, src/main/webapp/ui/src/components/Inputs/DynamicallyLoadedImageEditor.js, src/main/webapp/ui/src/components/Inputs/ImageField.js, src/main/webapp/ui/src/components/Inputs/__tests__/ImageField.test.js, src/main/webapp/ui/src/components/__tests__/ImageEditingDialog.test.js
This change replaces the image editor implemented with `@toast-ui/react-image-editor` -- which is no longer supported -- with one implemented mostly by us with use of the much smaller `react-image-crop` library. `react-image-editor` is not removed from the codebase yet, as it is also used by the Gallery, but once the Gallery has been migrated to the new UI code we will be able to remove this deprecated dependency, which will mean we will no longer have to pass `--force` to `npm install`.
=> RSDEV-339 Replace image editor in Inventory

DevDocs/DeveloperNotes/GettingStarted/Accessibility.md, src/main/webapp/ui/src/Inventory/components/FieldmarkImportDialog.js, src/main/webapp/ui/src/accentedTheme.js, src/main/webapp/ui/src/components/DialogBoundary.js, src/main/webapp/ui/src/eln-dmp-integration/Argos/DMPDialog.js, src/main/webapp/ui/src/eln-dmp-integration/Argos/__tests__/DMPDialog.test.js, src/main/webapp/ui/src/eln-dmp-integration/DMPOnline/DMPDialog.js, src/main/webapp/ui/src/eln-dmp-integration/DMPTool/DMPDialog.js, src/main/webapp/ui/src/eln/gallery/components/MoveToIrods.js, src/main/webapp/ui/src/eln/gallery/picker/index.js
This change adds a DialogTitle to various Dialogs that don't have one to meet the accessibility requirement that all dialogs have a label. Why this works is also documented to prevent such violations in the future.
=> Correct missing labels on dialogs

src/main/webapp/ui/.eslintrc, src/main/webapp/ui/package-lock.json, src/main/webapp/ui/package.json
To encourage better documentation practices, this change enforces all JS exports from one module to the rest of the codebase to have a comment. Ideally this comment should explain anything that the calling code from a different module needs to know about the implementation details of the export e.g. that it can throw an error, the behaviour of edge-cases, performance caveats, etc.
=> Enforce comments on exports

src/main/webapp/ui/src/common/useOauthToken.js, src/main/webapp/ui/src/eln/gallery/components/useIrods.js
This change
* Refresh the API token even if it is retrieved from session storage (previously this was only happening when the token was got from the API).
* Document clearly how the custom hook works, why we persist the token in session storage and in the hook, and the importance of refreshing the token in both cases.
* Fix iRods custom hook that was storing the token, and thus stopped working when the token expired.
=> RSDEV-294 Ensure API token is refreshed

src/main/java/com/researchspace/linkedelements/TextFieldEmbedIframeHandler.java, src/main/resources/velocityTemplates/textFieldElements/embedIframe.vm, src/test/java/com/researchspace/linkedelements/TextFieldEmbedIframeHandlerTest.java
When saving content of tinymce field to the back-end, the html is sanitized and potentially unsafe tags/attributes are removed. In particular we do remove `iframe` tags by default, but make exception for [youtube](https://documentation.researchspace.com/article/cdzdub1ykw-embedding-video-content-from-youtube) & [jove](https://documentation.researchspace.com/article/mopbqzzdf5-setting-up-jove-integration), as these are supported integrations.
The code in the PR adjusts whitelist of iframe `src` and other iframe attributes, so the latest embed fragments generated by Youtube & Jove are accepted.
Note that Jove integration doesn't work (Jove app on Apps page is scheduled for removal, see RSDEV-335), but we do want to allow directly embedded fragments to be pasted into RSpace tinyMCE.
=> RSDEV-367: fix jove and youtube embeds

src/main/webapp/ui/flow-typed/mui.js, src/main/webapp/ui/src/accentedTheme.js, src/main/webapp/ui/src/eln/gallery/chemistryIcon.js, src/main/webapp/ui/src/eln/gallery/common.js, src/main/webapp/ui/src/eln/gallery/components/InfoPanel.js, src/main/webapp/ui/src/eln/gallery/components/LinkedDocumentsPanel.js, src/main/webapp/ui/src/eln/gallery/components/MainPanel.js, src/main/webapp/ui/src/eln/gallery/components/Sidebar.js, src/main/webapp/ui/src/eln/gallery/filestoreIcon.js
To make the important information more obvious and show how information is related through visual hierarchies, this change tweaks how the new gallery is organised somewhat. It places the listing controls above both the listing and the info panel, changes the breadcrumbs into a series of chips/pills, and alters the typographical styles of the info panel subheadings.
=> RSDEV-434 Alter layout of new Gallery page

src/main/webapp/ui/src/eln/gallery/__tests__/useGalleryListing.test.js, src/main/webapp/ui/src/eln/gallery/components/Carousel.js, src/main/webapp/ui/src/eln/gallery/components/MainPanel.js, src/main/webapp/ui/src/eln/gallery/components/TreeView.js, src/main/webapp/ui/src/eln/gallery/useGalleryListing.js
After the user has performed an action, we need to refresh the UI to show the new state of their files and folders. Commit 8d05363d4d ensured that the refreshListing function set and unset the loading flag, thereby causing the listing components to be unmounted and remounted; which would result in all of the tree view nodes fetching their state again.
This, however, had a not-insignificant downside: in grid view, the listing would vanish and then re-appear after the refresh. Given that after any particular action most of the listing will remain unchanged (with just the odd file being deleted, duplicated, renamed, etc), it would be better if the content stayed visible and only updated once the new listing had been fetched.
This change fixes this by introducing a new flag to differentiate …
=> Various tweaks to refreshing of listings in new gallery

pom.xml, src/main/java/com/researchspace/dao/RecordGroupSharingDao.java, src/main/java/com/researchspace/dao/hibernate/RecordGroupSharingDaoHibernateImpl.java, src/main/java/com/researchspace/service/AutoshareManager.java, src/main/java/com/researchspace/service/RecordSharingManager.java, src/main/java/com/researchspace/service/cloud/impl/ShareRecordRequestHandler.java, src/main/java/com/researchspace/service/impl/AutoshareManagerImpl.java, src/main/java/com/researchspace/service/impl/RecordSharingManagerImpl.java, src/main/java/com/researchspace/service/impl/SharingHandlerImpl.java, src/main/java/com/researchspace/service/listeners/RecordAutoshareListener.java, src/test/java/com/researchspace/service/RecordManagerTest.java, src/test/java/com/researchspace/service/RecordSharingManagerIT.java, src/test/java/com/researchspace/service/RecordSharingTest.java, src/test/java/com/researchspace/testutils/BaseManagerTestCaseBase.java
The PR changes some internals of share/unshare action, to fix performance problem noticed when sharing with group of tens of users. The found bottleneck was in a fragment that was trying to establish into which shared folder the newly shared record should be placed. 
When sharing with a group, the old code was getting list of all members of the group and then was checking a) if the sharing user is allowed to share with every member of the group and b) what is the shared group folder of that group member. The loop there seems unnecessary, as a) when we establish that user is allowed to share with a group, we don't need to check it for every group member b) the same group's shared folder is referenced by individual shared folders of every group member, so it's enough to find one shared …
=> RSDEV-445: improved share/unshare performance, especially when sharing with large group

src/main/webapp/ui/src/eln/gallery/components/MainPanel.js, src/main/webapp/ui/src/eln/gallery/components/TreeView.js
When performing a drag-and-drop operation in the new Gallery's grid or tree view, the element being dragged around would be offset from the cursor by the amount that the scroll container of these views was scrolled by. The [dnd-kit docs recommend using a DragOverlay in these circumstances](https://docs.dndkit.com/api-documentation/draggable/drag-overlay#class-name-and-inline-styles:~:text=If%20your%20draggable%20item%20is%20within%20a%20scrollable%20container%2C%20we%20also%20recommend%20you%20use%20a%20%3CDragOverlay%3E).
By dragging around a semi-transparent overlay, it is also now easier to find the focussed dropzone under the cursor e.g. the quite small breadcrumb chips which can be used to more files to the hierarchy.
=> PRT-850 Use DragOverlay to avoid issue with dragging inside scroll container

src/main/webapp/ui/src/accentedTheme.js, src/main/webapp/ui/src/eln/gallery/components/AppBar.js, src/main/webapp/ui/src/eln/gallery/components/MainPanel.js, src/main/webapp/ui/src/eln/gallery/components/__tests__/MainPanel.test.js, src/main/webapp/ui/src/eln/gallery/index.js, src/main/webapp/ui/src/eln/gallery/picker/index.js
With the app bar being rolled out across more of the product to provide a unified navigation mechanism, including the search box in the app bar on the new gallery page suggests that the search is applied to the whole product. In reality, it is only applied to the current folder of the current gallery section, so it is best placed outside of the app bar.
=> RSDEV-386 Move new Gallery search out of app bar

src/main/java/com/researchspace/api/v1/model/RecordTreeItemInfo.java, src/main/java/com/researchspace/webapp/controller/GalleryController.java, src/test/java/com/researchspace/api/v1/controller/FolderApiControllerMVCIT.java
=> fix possible npe on attempt to retrieve parent folder of shared folder

src/main/webapp/ui/src/eln/sysadmin/users/__tests__/csvExport.test.js, src/main/webapp/ui/src/eln/sysadmin/users/__tests__/table.test.js, src/main/webapp/ui/src/eln/sysadmin/users/index.js
CSV export should include the precise byte count, rather than a human-friendly string, so that the column can be sorted in spreadsheet software.
=> RSDEV-562 Don't format filesize in CSV

pom.xml
Depending PR: https://github.com/rspace-os/dmptool-java-client/pull/7
AWS instance: http://dmponline-test.researchspace.com/ (mapped to http://rsdev-528-web-5.researchspace.com)
=> RSDEV-528: Fix DMPtool DMP not updated after exporting RSpace archive

Jenkinsfile, src/main/webapp/ui/.dependency-cruiser.js
Adds a Jenkins build step to verify that there aren't any dependency cruiser errors, such as using deprecated modules or importing npm modules directly without going through our wrappers.
=> Run depencency cruiser in jenkins

src/main/webapp/WEB-INF/pages/mediaGallery.jsp, src/main/webapp/scripts/pages/workspace/editor/documentEdit.js, src/main/webapp/scripts/pages/workspace/editor/tinymce5_configuration.js, src/main/webapp/scripts/pages/workspace/mediaGalleryManager.js
This PR fixes the problem of inserting attachment from chemical subgallery into tinymce, when chemistry is not available (disabled on System->Configuration screen). The behaviour is now consistent with drag&drop - if chemical file is used, the generic (miscellaneous) attachment template is used, with ring icon. Previously the code tried to do a chemical conversion, and when that failed, it was inserting a fragment that looked broken.
This can be tested on https://rsdev-585-insert-from-chem-gallery-4.researchspace.com/
=> when inserting chemical from Gallery use generic template if chemistry is disabled

src/main/java/com/axiope/service/cfg/BaseConfig.java, src/main/java/com/axiope/service/cfg/ProductionConfig.java, src/main/java/com/axiope/service/cfg/TestAppConfig.java, src/main/java/com/researchspace/api/v1/controller/SystemSettingsApiController.java, src/main/java/com/researchspace/service/SystemPropertyManager.java, src/main/java/com/researchspace/service/SystemPropertyName.java, src/main/java/com/researchspace/service/impl/RoRServiceManagerImpl.java, src/main/java/com/researchspace/service/impl/SystemConfigurationInitialisor.java, src/main/java/com/researchspace/service/impl/SystemPropertyManagerImpl.java, src/main/java/com/researchspace/webapp/controller/DeploymentPropertiesController.java, src/main/java/com/researchspace/webapp/integrations/snapgene/DNAViewerController.java, src/main/resources/deployments/defaultDeployment.properties, src/test/java/com/researchspace/api/v1/controller/API_MVC_TestBase.java, src/test/java/com/researchspace/service/GroupManagerTest.java, src/test/java/com/researchspace/service/IntegrationsHandlerCachingTest.java, src/test/java/com/researchspace/service/SystemPropertyManagerIT.java, src/test/java/com/researchspace/service/SystemPropertyManagerTest.java, src/test/java/com/researchspace/service/UserProfileManagerTest.java, src/test/java/com/researchspace/service/impl/IntegrationsHandlerTest.java, src/test/java/com/researchspace/service/impl/SystemConfigurationInitializorTest.java, src/test/java/com/researchspace/webapp/controller/GroupControllerMVCIT.java, src/test/java/com/researchspace/webapp/controller/RoRSysAdminControllerMVCIT.java, src/test/java/com/researchspace/webapp/controller/SystemAndDeploymentPropsControllerMVCIT.java, src/test/java/com/researchspace/webapp/controller/UserProfileControllerMVCIT.java, src/test/java/com/researchspace/webapp/controller/WorkspaceControllerTest.java, src/test/java/com/researchspace/webapp/integrations/orcid/OrcidControllerTest.java, src/test/java/com/researchspace/webapp/integrations/snapgene/DNAViewerControllerTest.java
The main functional change in this PR is adding `SystemConfigurationInitialisor` class (and test), which runs on RSpace startup and checks if deployment properties connected to chemistry are configured. If these are not configured, the initializor disables 'chemistry.available' system setting (visible on System -> Configuration -> Settings page). Disabling that setting means users will not be able to use chemistry features, which is what we want as the features won't work without proper configuratino - that's different from old chemaxon engine, where even misconfigured setup still allowed chemical calculations being run, as most of them was based on chemaxon libraries bundled within RSpace.
But then, when working on the PR, I've noticed that backend code that tries to read/update system …
=> RSDEV-550: disable chemistry on startup

src/main/webapp/ui/src/components/AccentMenuItem.js.flow, src/main/webapp/ui/src/components/AccentMenuItem.tsx, src/main/webapp/ui/src/components/AppBar/index.tsx, src/main/webapp/ui/src/eln/gallery/components/MainPanel.js
This change adds support for aria-current to the AccentMenuItem component, utilising the prop in the nav app bar and the gallery to enhance the accessibility of the menus that use the AccentMenuItem component.
This change was pulled out of RSDEV-570, as it requires the use of the current marker for menus.
=> RSDEV-570 Add aria-current support to AccentMenuItem

src/main/webapp/ui/src/Inventory/components/ContextMenu/PrintBarcodeAction.js, src/main/webapp/ui/src/Inventory/components/Fields/Barcodes/FieldCard.js, src/main/webapp/ui/src/Inventory/components/Fields/Barcodes/PrintContents.js, src/main/webapp/ui/src/Inventory/components/Fields/Barcodes/PrintDialog.js, src/main/webapp/ui/src/Inventory/components/Print/PrintContents.js, src/main/webapp/ui/src/Inventory/components/Print/PrintDialog.js, src/main/webapp/ui/src/Inventory/components/Print/__tests__/PrintDialog.test.js
In Inventory, we have a mechanism of printing a record's QR code onto a label. This change re-uses this functionality for printing QR codes to IGSN DOIs in layout analogous to raffle books, wherein each IGSN is printed twice to aid with offline record keeping of used IGSNs.
This change
1. On all print outs, the Global Id of the parent container (labelled "Location") is replaced with the URL of the container, as that would be more useful on a printout.
2. Splits the functionality that allows for the printing of all of the barcodes associated with a particular record (figure 1) from that of the functionality for printing the first barcode associated with each record (figure 2). This is because the latter can be re-used for IGSNs given the 1-to-1 mapping between Inventory records and …
=> RSDEV-518 Add support for IGSNs to print action

src/main/webapp/ui/src/Toolbar/Workspace/Misc/NewNotebook.js
This just back ports the submit button component that we now use across the new parts of the codebase to the old new-notebook dialog.
=> RSDEV-641 Add a loading spinner to new notebook dialog's submit button

src/main/webapp/ui/.eslintrc, src/main/webapp/ui/src/eln/sysadmin/users/index.spec.tsx
This is an experiment to structure the playwright component tests in such a way that the non-coders in the team can feasibly read the tests to understand the behaviour of the system. To do this, the keywords for the gherkin syntax of BDD are re-used to break the tests down into a series of re-usable steps
=> Playwright component testing experimenting, using BDD style keywords to structure the tests

src/main/webapp/scripts/externalTinymcePlugins/mathjax/dialog.html
The old link went 404. Updated with a new LaTeX cheat sheet link that points to a new resource
=> Update LaTeX cheat sheet pdf link

src/main/webapp/WEB-INF/pages/system/settings_ajax.jsp
This change tweaks the text at the top of the sysadmin config page to make clear to sysadmins that some configurations options are made via changes to the deployment properties and other config files, rather than solely through the web-based UI.
This change does not modify `system.settings.header.info` so as to not change the community admin settings dialog
=> RSDEV-268 Link to additional server properties docs

src/main/java/com/researchspace/dao/RSChemElementDao.java, src/main/java/com/researchspace/dao/hibernate/RSChemElementDaoHibernate.java, src/main/java/com/researchspace/service/impl/RSChemElementManagerImpl.java, src/test/java/com/researchspace/service/RSChemElementMgrTest.java
This PR makes a few changes to RSpace-side of collecting chemical search results:
* main change is that `RSChemElementDaoHibernate` now calls `getSession().clear();` after collecting a set of chemistry results, which stops possible out-of-memory exception, which could happen when method was called multiple times during processing single search request
* another minor performance change on DAO level is using `READ_ONLY` query hint, that is fine as we only read the results (i.e. show them on search results page)
* on manager level, in `RSChemElementManagerImpl.getFilteredChemSearchedItems()` method, the order of checks is reverted when checking if given document, which contains a matching chemical hit, should be displayed to the user.
The first two changes shouldn't be controversial, but on …
=> RSDEV-665: chemical search performance fixes 

src/main/java/com/researchspace/service/impl/DocumentCopyManagerImpl.java, src/test/java/com/researchspace/chemistry/ChemistryDocumentCopyIT.java
When a document is copied, the chemical element was saved via the dao layer rather than manager layer, which meant the call to save the chemical to rspace document pair to the chemistry service was bypassed. 
This meant the copied document wouldn't be returned as a search hit when searching for the chemical element. 
The fix is to save the copied document via the manager rather than the dao layer.
As the test requires an instance of the chemistry service, it's been ignored in the open-source build, which is the case for other chemistry-dependent tests. 
I've created https://researchspace.atlassian.net/browse/RSDEV-673 with some ideas on how to handle these tests in a nicer way. 
I'll enable this test in the closed-source repo once it's been synced.
Passing Jenkins build here: …
=> RSDEV-633 Save chemicals in copied documents to the chemistry service

src/main/webapp/ui/src/components/ValidatingSubmitButton.spec.tsx, src/main/webapp/ui/src/components/ValidatingSubmitButton.story.tsx
This change defines a complete suite of playwright component tests for the ValidatingSubmitButton, a component that is used across the product to ensure that users only submit forms with valid data.
Disabling the button and marking the invalid fields with error messages is a more common UI design, but I think this can often result in it not being clear as to why a form cannot be submitted, especially when the invalid field is no longer on screen. There is nothing more annoying than a disabled button, but everything looks fine, and there's no explanation why! Instead, this component jiggles and display a little popup with the reasoning for why the user may not proceed.
What this change does is provide a complete test suite for this component, now that we have playwright component testing. …
=> Complete test suite for ValidatingSubmitButton

src/main/webapp/WEB-INF/pages/userform.jsp
When generating or regenerating an API key, the user is now presented with a warning about the security implications of using API keys.
N/A
To test, just generate or regenerate an API key from My RSpace.
=> Add warning text to API key password confirmation dialog

src/main/java/com/researchspace/api/v1/controller/InventoryFilesApiController.java, src/main/java/com/researchspace/service/impl/DocumentCopyManagerImpl.java, src/test/java/com/researchspace/api/v1/controller/InventoryFilesApiControllerTest.java
When a chemistry file attachment to an Inventory item was opened in Ketcher, the contents of the file were first being converted to the "default" format before being read by Ketcher. This causes some information to be lost, and is needless. 
The fix is to load the file in it's original format, using `ChemistryProvider.convert(File)` which reads the file contents, handling conversion to base64 if the file is a `.cdx`. This same fix was applied in other cases where files are loaded into Ketcher.
before:
after:
=> Rsdev 611 fix ketcher preview inventory

src/main/webapp/ui/src/Inventory/Container/NewRecordForm.js, src/main/webapp/ui/src/Inventory/Sample/NewRecordForm.js, src/main/webapp/ui/src/Inventory/Template/NewRecordForm.js, src/main/webapp/ui/src/Inventory/components/Fields/Name.js, src/main/webapp/ui/src/Inventory/components/Stepper/SynchroniseFormSections.js
* Mark the field with a red asterisk to indicate that it is required
* Always show the overview section of the new-record forms, ignoring the persisted state
* If the overview section is closed, show the red indicator that there is an error inside
This is intended to making it clearer that the name field is required when creating new records.
None
=> RSDEV-676 Make clear that name field is required when creating new Inventory records

src/main/webapp/ui/src/Inventory/components/FieldmarkImportDialog.js, src/main/webapp/ui/src/components/DataGridWithRadioSelection.js.flow, src/main/webapp/ui/src/components/DataGridWithRadioSelection.spec.tsx, src/main/webapp/ui/src/components/DataGridWithRadioSelection.story.tsx, src/main/webapp/ui/src/components/DataGridWithRadioSelection.tsx, src/main/webapp/ui/src/eln-dmp-integration/Argos/DMPDialog.spec.tsx, src/main/webapp/ui/src/eln-dmp-integration/Argos/DMPDialog.tsx, src/main/webapp/ui/src/eln-dmp-integration/DMPOnline/DMPDialog.tsx, src/main/webapp/ui/src/eln-dmp-integration/DMPTool/DMPDialog.tsx
This change introduces a new react component -- DataGridWithRadioSelection -- that provides a generalised mechanism for providing a table from which the user must select a single row. This is more robust than the solutions used in DMPonline, DMPTool, and Argos dialogs whilst also reducing duplication.
The four dialogs have not yet been tested and the code AI generated, so they definitely need testing.
I've tested on Fieldmark, by mocking the network call that lists its notebooks
=> Data grid with radio selection

src/main/java/com/researchspace/api/v1/controller/OAuthClientController.java, src/main/java/com/researchspace/service/SystemPropertyName.java, src/main/resources/bundles/system/system.properties, src/main/resources/sqlUpdates/changeLog-rsdev-365.xml, src/main/resources/sqlUpdates/liquibase-master.xml, src/main/webapp/WEB-INF/pages/system/settings_ajax.jsp, src/main/webapp/scripts/pages/system/settings_mod.js, src/test/java/com/researchspace/webapp/controller/MVCTestBase.java, src/test/java/com/researchspace/webapp/controller/OAuthAPIAccessMVCIT.java, src/test/java/com/researchspace/webapp/controller/OAuthClientCommunityControllerMVCIT.java, src/test/java/com/researchspace/webapp/controller/OAuthClientControllerMVCIT.java, src/test/java/com/researchspace/webapp/controller/OAuthClientSSOControllerMVCIT.java
The PR adds new system setting `api.oauth.authentication`, which is set to DENIED by default. That stops oauth authentication endpoint from generating tokens, unless Sysadmin explicitly allows it.
The setting is available just for System Admins (not on Community level), on System -> Configuration -> System Settings page;
Can be tested by trying OAuth login option in swagger docs (at `/public/apiDocs`).
=> RSDEV-653: oauth authentication enabled by system setting

pom.xml, src/main/java/com/researchspace/api/v1/InventoryIdentifiersApi.java, src/main/java/com/researchspace/api/v1/controller/InventoryIdentifiersApiController.java, src/main/java/com/researchspace/api/v1/model/ApiInventoryDOI.java, src/main/java/com/researchspace/service/inventory/ApiIdentifiersHelper.java, src/main/java/com/researchspace/service/inventory/InventoryIdentifierApiManager.java, src/main/java/com/researchspace/service/inventory/impl/ContainerApiManagerImpl.java, src/main/java/com/researchspace/service/inventory/impl/InventoryIdentifierApiManagerImpl.java, src/main/java/com/researchspace/service/inventory/impl/SampleApiManagerImpl.java, src/main/java/com/researchspace/service/inventory/impl/SubSampleApiManagerImpl.java, src/main/webapp/WEB-INF/pages/public/apiDocs.jsp, src/main/webapp/resources/rspace_api_inventory_specs_1_111_0.yaml, src/test/java/com/researchspace/api/v1/controller/InventoryIdentifiersApiControllerMVCIT.java, src/test/java/com/researchspace/service/inventory/InventoryIdentifierApiManagerTest.java, src/test/java/com/researchspace/webapp/integrations/datacite/DataCiteConnectorDummy.java
The following PR is merged and a new model version is built: https://github.com/rspace-os/rspace-core-model/pull/26
- Allowing the users to assign an already unassociated identifier to an inventory item
- The search has been improved so now users  can search by DOI or a substring of a DOI
=> RSDEV-617: Allow users to manually associate IGSN IDs to a sample in Inventory

src/main/webapp/ui/package-lock.json, src/main/webapp/ui/package.json, src/main/webapp/ui/playwright-ct.config.ts
@nebay-abraha's great suggestion to use `getPort` to prevent issues with running multiple instances of playwright component testing in parallel.
As background, Playwright components testing spins up a webserver to serve simple HTML pages including just the React component under test, which are then visited by the headless browser. By hardcoding the port number, we were preventing multiple instances of the Playwright component test runner from executing in parallel because they would all attempt to acquire the same port.
=> Dynamically assign playwright port

src/main/java/com/researchspace/service/inventory/impl/InventoryIdentifierApiManagerImpl.java, src/test/java/com/researchspace/service/inventory/InventoryIdentifierApiManagerTest.java
User can now search a DOI inserting the url without protocol i.e.: `doi.org/10.86724/n1c0-t35t`
=> RSDEV-617: Adding the facility to search DOI without the URL protocol (i.e.: https)

.gitignore, pom.xml, src/main/java/com/researchspace/api/v1/auth/AbstractApiAuthenticator.java, src/main/java/com/researchspace/api/v1/auth/CombinedApiAuthenticator.java, src/main/java/com/researchspace/api/v1/service/impl/ApiRequestLogger.java, src/main/java/com/researchspace/service/inventory/impl/InventoryIdentifierApiManagerImpl.java, src/main/resources/log4j2-dev.xml, src/main/resources/log4j2.xml
The PR adds new server log `ApiRequests.txt` that adds an entry anytime the external API client makes a request to the public API.
Example content of the new log file:
```
03 Jun 2025 08:05:21,360 - POST [/app/api/v1/sysadmin/groups] from 3.10.136.135, for user [sysadmin1] (API_KEY)
03 Jun 2025 09:12:28,959 - GET [/app/api/v1/documents] from 3.11.69.118, for user [matthias] (API_OAUTH_TOKEN)
03 Jun 2025 09:15:10,753 - GET [/app/api/v1/documents/297] from 3.11.69.118, for user [matthias] (API_OAUTH_TOKEN)
```
Additionally, the PR fixes the issue with external API call trying to reuse active Shiro session, which was happening when the user was logged into UI at the same time as making API call. The session reusage was causing such calls to not be recognized as external API calls, and …
=> RSDEV-652: api usage log

Jenkinsfile, src/main/resources/sqlUpdates/changeLog-0.15.xml, src/main/resources/sqlUpdates/changeLog-0.16.xml, src/main/resources/sqlUpdates/changeLog-1.37.xml, src/main/resources/sqlUpdates/changeLog-1.49.xml, src/main/resources/sqlUpdates/changeLog-1.91.xml, src/main/resources/sqlUpdates/data-changeLog.xml, src/test/java/com/researchspace/api/v1/auth/CombinedApiAuthenticatorTest.java
I believe that context is no longer needed, and it is likely reason for recent problems with jenkins nightly test run.
=> remove 'liquibase-update-test' liquibase context

src/main/webapp/ui/src/stores/models/ImportModel.ts
When on the subsamples import page, we were comparing the template definition to the custom fields of the parsed subsamples CSV file (which will always be empty). A warning would then say that there was a problem with the samples import, but there wasn't.
=> PRT-950 Fix incorrect import samples warning

src/main/webapp/ui/src/stores/models/ImportModel.ts
The API now supports importing IGSNs as part of Inventory's CSV import. This change tweaks to the UI to utilise this API change to be able to support the IGSN import in the UI.
=> RSDEV-685 Update UI to support IGSN CSV import

src/main/java/com/axiope/service/cfg/ProductionConfig.java, src/main/java/com/axiope/service/cfg/TestAppConfig.java, src/main/java/com/researchspace/service/inventory/impl/InventoryImportManagerImpl.java, src/test/java/com/researchspace/service/inventory/impl/InventoryImportManagerTest.java
- Fix Tags were not set when importing containers from CSV into Inventory. 
- Some import cleaning by from the maven plugin
- To test in AWS https://rsdev-694-fix-tags-container-csv-5.researchspace.com/ you can submit the CSV that is attached to the JIRA ticket RSDEV-694
=> RSDEV-694: Fix Tags were not created when import Container from CSV into Inventory

src/main/java/com/researchspace/api/v1/controller/GalleryIrodsApiController.java, src/main/java/com/researchspace/netfiles/NfsClient.java, src/main/java/com/researchspace/netfiles/irods/IRODSClient.java, src/test/java/com/researchspace/api/v1/controller/GalleryIrodsApiControllerTest.java
The PR fixes problem with 'move to iRODS' action executed on filestores created through a new Gallery UI. 
The problem is that iRODS jargon library action for uploading files requires absolute file path to the destination location on target iRODS server. The other jargon library actions, e.g. ones used for browsing the content of iRODS filestore, are fine with relative file paths ('relative' here means relative to irods home directory, saved on filesystem details page). 
It turns out that iRODS filestores saved by the new Gallery UI are saving relative filestore paths (this seems like a change of the behaviour from old Gallery, which we didn't notice). The relative filestore paths should be fine though, we do use them for samba/sftp filestores, it's just that when the absolute path is …
=> RSDEV-706: when moving/copying to irods, ensure the absolute path is used

src/main/webapp/scripts/pages/journal.js
The PR changes the way how temporary notebook data is stored on a page during loading of the notebook view. Previously this data was stored within `<div>` element as html, and as a consequence various js/react code selectors were matching the temporary data fragment. That was causing front-end to make duplicated calls e.g. to `/listOfMaterials/forField/` and `/chemical/ajax/getInfo` endpoints.
Now that temporary notebook data is stored as text, it no longer triggers any js/react code.
=> RSDEV-729: store temporary notebook data on page as text, rather than html

src/main/java/com/researchspace/webapp/controller/WorkspacePermissionsDTOBuilder.java, src/main/webapp/WEB-INF/pages/workspace_ajax.jsp, src/main/webapp/scripts/pages/workspace.js
This PR allows to see the following 3 create menu entries everywhere the user has the createMenu permission:
- "From Word"
- "From protocol.io"
- "From Evernote"
- Be sure to be in a shared folder (or a shared notebook) where you have permission to create itmes 
- - WHEN Push the "CREATE" button
- - THEN you should be able to see the 3 entries that have been unlocked
=> RSDEV-710: Show "create from 3rd party" everywhere

pom.xml, src/main/java/com/researchspace/webapp/controller/JournalController.java, src/main/webapp/scripts/pages/journal.js, src/main/webapp/scripts/tags/fileTreeBrowser.js, src/test/java/com/axiope/service/cfg/ProdProfileTestConfig.java, src/test/java/com/researchspace/webapp/controller/JournalControllerMVCIT.java
This PR removes `/journal/ajax/entryIndex` endpoint that front-end was using during opening of notebook view, if it didn't know the position of the entry within the notebook (as the server-side was only supporting retrieving notebook entry by its position). Now the entry data can be retrieved either by position of the entry within notebook (old way), or just with id of the entry (new way) - with new `/journal/ajax/retrieveEntryById` endpoint. As a result, front-end code method `loadEntryById` may now start loading entry details immediately after page is rendered, rather than waiting for response with the position of the entry.
=> RSDEV-733: remove unnecessary round-trip call when loading notebook entry

src/main/java/com/researchspace/service/inventory/csvimport/InventoryImportSampleFieldCreator.java, src/test/java/com/researchspace/service/inventory/csvimport/InventoryImportSampleFieldCreatorTest.java
- The CSV import was suggesting that a field could be mapped to an identifier in case all the values were empty
***OPTIONAL***
- WHEN import a CSV with a coulmn that has all values empty
- THEN the repsonse MUST NOT suggest the column as identifier
=> PRT-951: Fix CSV import suggesting "identifier" field also when all the values are empty

src/main/java/com/researchspace/webapp/controller/DashboardController.java
It's the notifications listing that is shown by default, and so the `/dashboard` endpoint should call notifications preparation after messages preparation, so the common elements (e.g. pagingation) are not overridden.
=> revert call order so notification pagination is calculated last

src/main/java/com/researchspace/linkedelements/TextFieldEmbedIframeHandler.java, src/main/java/com/researchspace/service/RecordManager.java, src/main/java/com/researchspace/service/impl/RecordManagerImpl.java, src/main/java/com/researchspace/service/impl/SharingHandlerImpl.java, src/main/java/com/researchspace/webapp/controller/NotebookEditorController.java, src/main/java/com/researchspace/webapp/controller/StructuredDocumentController.java, src/main/java/com/researchspace/webapp/integrations/protocolsio/ProtocolsIOController.java, src/main/java/com/researchspace/webapp/integrations/protocolsio/ProtocolsIOToDocumentConverter.java, src/main/java/com/researchspace/webapp/integrations/protocolsio/ProtocolsIOToDocumentConverterImpl.java, src/main/webapp/WEB-INF/pages/notebookEditor/notebookMainPanel.jsp, src/main/webapp/WEB-INF/pages/workspace.jsp, src/main/webapp/WEB-INF/tags/importFromProtocolsIo.tag, src/main/webapp/scripts/externalTinymcePlugins/protocols_io/js/main.js, src/main/webapp/scripts/pages/workspace.js, src/test/java/com/researchspace/linkedelements/TextFieldEmbedIframeHandlerTest.java, src/test/java/com/researchspace/service/RecordManagerTest.java, src/test/java/com/researchspace/webapp/controller/RecordManagerStub.java, src/test/java/com/researchspace/webapp/controller/StructuredDocumentControllerTest.java, src/test/java/com/researchspace/webapp/integrations/protocolsio/ProtocolsIOControllerMVCIT.java, src/test/java/com/researchspace/webapp/integrations/protocolsio/ProtocolsIOControllerTest.java, src/test/java/com/researchspace/webapp/integrations/protocolsio/ProtocolsIOConverterTest.java
When creatng from Word/Evernote (or protocols.io) the process was failing for a ermisisons issue
In this PR we have extended the `create` permissions in those cases to allow the user to create also if is a SharedFolder or a SharedNotebook
To test you can create from Word/Evernote or protocols.io from inside a shared notebook made by another user of the same group
- AWS instance: https://prt-957-create-from-word-16.researchspace.com
-  - you need to configure `protocolsio.client.id` and `protocolsio.secret` in the deployment.properties
=> RSDEV-957: Fix Permission issue when creating from Word (or creating from protocols.io) in a shared folder/notebook

src/main/webapp/ui/src/components/AppBar/index.spec.tsx, src/main/webapp/ui/src/components/AppBar/index.tsx
The apps page doesn't need a second, hidden, h1 as it already has one and it would be an accessibility violation to have two. The principle in theory applies to all other pages that do not appear as tabs in the app bar as they too should have titles for sighted users as there is no indication in the app bar what page the user is currently on.
=> Remove hidden heading from apps page app bar

pom.xml, src/main/java/com/researchspace/service/fieldmark/impl/FieldmarkServiceClientAdapterImpl.java, src/main/java/com/researchspace/webapp/integrations/fieldmark/FieldmarkApiController.java
This PR fixes the import to fail when on FIeldmark there is any of the field as empty
- In order to test you need to:
-  - create a new observation on FieldmarkUI with all the fields as null and THEN import from Fieldmark in RSpace
-  - amend and existing observation on FIeldmarkUI by nullifying few fields (especially location and picture) and THEN import from Fieldmark in RSpace
=> RSDEV-740: Fix Empty fields in Fieldmark cause import to fail

src/main/webapp/styles/rs-global.css
The PR changes the default on-hover cursor shown over Workspace listing, so the user has better chance of clicking on the active part of the row.
=> RSDEV-754: use default cursor when hovering over unclickable part of workspace listing

src/main/webapp/scripts/tags/fileTreeBrowser.js
Adds the null check to recently-modified fileTreeBrowser code
=> PRT-967: fix problem with switching Workspace to tree-view mode

src/main/webapp/ui/src/Inventory/Search/SearchRouter.tsx
Regression introduced by the TypeScript migration that caused some network calls to be made twice. Doesn't appear that there was any bug visible to the user, just inefficient network usage
=> RSDEV-761 Remove useEffect dependencies that trigger excess network calls

src/main/java/com/researchspace/webapp/controller/PerformanceLoggingInterceptor.java, src/main/java/com/researchspace/webapp/filter/LocaleFilter.java, src/main/resources/log4j2-dev.xml, src/main/resources/log4j2.xml
RSpace by default logs slow requests into `SlowRequests.txt` log by using `PerformanceLoggingInterceptor`, but that interceptor really measures the time taken by the MVC Controller class. It seem that in some cases the total time taken by the RSpace webapp is significantly longer longer than value reported by the interceptor.
This PR adds a few additional lines that'd log time required for processing request on web filter level. To enable that additional log entries uncomment the line in `log4j2.xml`.
=> RSDEV-760: optional logging of request processing time on web filter level

pom.xml, src/main/java/com/researchspace/api/v1/FieldmarkApi.java, src/main/java/com/researchspace/model/dtos/fieldmark/FieldmarkNotebookDTO.java, src/main/java/com/researchspace/service/fieldmark/FieldmarkServiceClientAdapter.java, src/main/java/com/researchspace/service/fieldmark/FieldmarkServiceManager.java, src/main/java/com/researchspace/service/fieldmark/impl/FieldmarkServiceClientAdapterImpl.java, src/main/java/com/researchspace/service/fieldmark/impl/FieldmarkServiceManagerImpl.java, src/main/java/com/researchspace/service/fieldmark/impl/FieldmarkToRSpaceApiConverter.java, src/main/java/com/researchspace/webapp/integrations/fieldmark/FieldmarkApiController.java, src/main/java/com/researchspace/webapp/integrations/fieldmark/FieldmarkApiImportRequest.java, src/main/java/com/researchspace/webapp/integrations/fieldmark/FieldmarkApiImportResult.java, src/main/resources/applicationContext-service.xml, src/main/webapp/WEB-INF/pages/public/apiDocs.jsp, src/main/webapp/resources/rspace_api_inventory_specs_1_113_0.yaml, src/test/java/com/researchspace/service/FieldmarkServiceClientAdapterRealConnectionTest.java, src/test/java/com/researchspace/service/fieldmark/impl/FieldmarkServiceClientAdapterTest.java, src/test/java/com/researchspace/service/fieldmark/impl/FieldmarkServiceManagerTest.java, src/test/java/com/researchspace/webapp/integrations/fieldmark/FieldmarkApiControllerRealConnectionTest.java, src/test/java/com/researchspace/webapp/integrations/fieldmark/FieldmarkApiControllerTest.java, src/test/java/com/researchspace/webapp/integrations/fieldmark/FieldmarkRealConnectionMVCIT.java, src/test/resources/TestResources/fieldmark/notebookDTO-singleRecord.json, src/test/resources/TestResources/fieldmark/records.json
- This PR extends the functionality "Import from Fieldmark"
- - From now when importing from fieldmark the system will analyse all the rows and returns a list of candidate fields that can be used as DOI identifiers. Finally the user will be able select one of the candidate fields to be treated as IGSN DOI Identifier. Finally, when importing the fieldmark notebook into the inventory, the Samples will already have the DOI linked as specified on the Fieldmark UI.
- merge the fieldmark repo PR: https://github.com/rspace-os/fieldmark-java-client/pull/4
- I have alreadsy prefilled the "`Description`" field into Fieldmark UI to have DOIs.
- If you want to test on an instance you need to be sure that those DOIs are already generated on the RSpace instance and are not assigned to any inventory …
=> RSDEV-520: Extend Fieldmark import with IGSN ID

src/main/java/com/researchspace/service/RecordManager.java, src/main/java/com/researchspace/service/impl/RecordManagerImpl.java, src/main/java/com/researchspace/service/impl/SharingHandlerImpl.java, src/main/java/com/researchspace/webapp/controller/NotebookEditorController.java, src/main/java/com/researchspace/webapp/controller/StructuredDocumentController.java, src/main/java/com/researchspace/webapp/controller/WorkspaceController.java, src/main/java/com/researchspace/webapp/integrations/protocolsio/ProtocolsIOController.java, src/test/java/com/researchspace/service/RecordManagerTest.java, src/test/java/com/researchspace/webapp/controller/RecordManagerStub.java, src/test/java/com/researchspace/webapp/controller/StructuredDocumentControllerTest.java, src/test/java/com/researchspace/webapp/controller/WorkspaceControllerMVCIT.java, src/test/java/com/researchspace/webapp/integrations/protocolsio/ProtocolsIOControllerTest.java
Previously the check in code was assuming that if notebook is shared, the move action should try sharing into notebook. But that's not true if user has permission to directly add things into notebook (e.g. they are a notebook owner), in that case we should do normal move.
The actual code fix is just one line in `WorkspaceController` (well, plus a new method in `RecordManager` and a unit test). The rest of changeset for this PR comes from fixed typo in adjacent method name.
=> RSDEV-775: allow direct move of docs into owned shared notebook 

Jenkinsfile
Clear the playwright cache before each run on Jenkins. This may have some performance hit, but it is better than the build randomly failing because the cache needs flushing
=> clear playwright cache before running

src/main/webapp/ui/src/accentedTheme.ts, src/main/webapp/ui/src/components/SubmitSpinnerButton.tsx, src/main/webapp/ui/src/components/ValidatingSubmitButton.spec.tsx, src/main/webapp/ui/src/components/ValidatingSubmitButton.story.tsx
This changes fix the issue where the buttons with the `callToAction` colour would not have sufficient contrast when the user has enabled a high contrast mode in their browser. 
In addition to fixing the issue, this change also adds a test for ValidatingSubmitButton, one of the main use cases for the `callToAction` colour that asserts that the button has sufficient contrast to meet the AAA threshold of the WCAG 2.2 standard when the browser is requesting additional contrast. This is not simple to do because the MUI Button's ripple effect normally prevents automated accessibility testing tools like axe from being able to assert the foreground and background colours as they cannot be certain what text is actually visible. As such, we remove the ripple to be able to assert the colours.
=> PRT-979 Fix callToAction colour in high contrast mode

src/main/java/com/researchspace/service/impl/GroupManagerImpl.java, src/main/java/com/researchspace/service/impl/MediaManagerImpl.java, src/main/java/com/researchspace/service/impl/UserContentUpdaterImpl.java, src/main/java/com/researchspace/webapp/controller/FolderToDisplayInMoveDialogFilter.java, src/test/java/com/researchspace/service/AttachmentSearchTest.java, src/test/java/com/researchspace/service/FolderOrganisationAndApiInboxFolderTest.java, src/test/java/com/researchspace/service/GroupManagerTest.java
The PR moves call of `indexFile(media);` few lines down, so when method is called, the `media.fileProperty` is updated to the new property. Previously, the indexing was run with the old `fileProperty`, so subsequent search couldn't find the connected record.
The real changes are just in two classes: `MediaManagerImpl.java` and `AttachmentSearchTest.java`, other files in the PR are just a spotless formatting missing from previous merges.
=> RSDEV-755: correctly index doc-type gallery attachment when uploading new version

src/main/webapp/scripts/externalTinymcePlugins/toolbar/scripts/index.js, src/main/webapp/scripts/pages/workspace/editor/tinymce5_configuration.js
This change fixes #475 wherein it was possible for the user to remove the second TinyMCE toolbar, which the code that adds toolbar buttons for the various integrations assumes will always be there. This PR makes two changes
1. When the user is customising the toolbar, they are prevented from removing the second toolbar
2. When registering toolbar buttons for the various integrations, we now create additional toolbars to ensure that we can add the new toolbar buttons to the second toolbar. This catches cases where users have already broken their toolbars or where the second toolbar may be removed through any other mechanism.
=> Fix bug where TinyMCE had only one toolbar

pom.xml, src/main/java/com/researchspace/api/v1/model/ApiDocumentInfo.java, src/main/java/com/researchspace/api/v1/service/impl/RecordApiManagerImpl.java, src/main/java/com/researchspace/model/dtos/WorkspaceListingConfig.java, src/main/java/com/researchspace/model/dtos/WorkspaceSettings.java, src/main/java/com/researchspace/service/FolderManager.java, src/main/java/com/researchspace/service/impl/FolderManagerImpl.java, src/main/java/com/researchspace/service/impl/RecordDeletionManagerImpl.java, src/main/java/com/researchspace/webapp/controller/NotebookEditorController.java, src/main/java/com/researchspace/webapp/controller/WorkspaceController.java, src/main/java/com/researchspace/webapp/controller/WorkspacePermissionsDTOBuilder.java, src/main/webapp/WEB-INF/tags/record_editor_link.tag, src/main/webapp/WEB-INF/tags/record_icon.tag, src/main/webapp/resources/rspace_api_specs_1_115_0.yaml, src/main/webapp/scripts/global.js, src/main/webapp/scripts/pages/notebookEditor.js, src/main/webapp/scripts/pages/workspace/editor/documentView.js, src/main/webapp/scripts/tags/fileTreeBrowser.js, src/test/java/com/researchspace/service/FolderManagerSpringTest.java, src/test/java/com/researchspace/webapp/controller/FolderManagerStub.java, src/test/java/com/researchspace/webapp/controller/NotebookEditorControllerTest.java
- This PR fixes 2 bug scenarios:
- - [`CREATE` button is showed for PI when reaching `sharedNotebook` from another user's path](https://researchspace.atlassian.net/browse/RSDEV-823)
- - [`CREATE` button is shown on notebook editor when it should not be](https://researchspace.atlassian.net/browse/RSDEV-819)
- Please refer to the JIRA tickets in order to check the step to reproduce
- 🔴  OLD AWS instance: https://rsdev-819-create-button-26.researchspace.com/ (bug)
- 🟢  NEW AWS instance: https://rsdev-819-create-button-28.researchspace.com/
=> [RSDEV-819][RSDEV-823]: Fix `CREATE` button that was shown when it should have not

pom.xml, src/main/java/com/researchspace/webapp/controller/NotebookEditorController.java, src/main/java/com/researchspace/webapp/controller/StructuredDocumentController.java, src/main/java/com/researchspace/webapp/controller/WorkspaceController.java, src/main/java/com/researchspace/webapp/integrations/protocolsio/ProtocolsIOController.java, src/test/java/com/researchspace/webapp/controller/NotebookEditorControllerTest.java
This PR fixes the iussue where an user could not import from WORD when located on the top level of the workspace.
- This PR needs to be merged first: https://github.com/rspace-os/rspace-core-model/pull/42
- Please refer to the JIRA ticket https://researchspace.atlassian.net/browse/PRT-995 for the steps to reproduce
- AWS instance: https://prt-995-web-3.researchspace.com/
=> [PRT-995][PRT-997]: Fix `import from word` and errors connected to `grandParentId`

src/main/java/com/researchspace/api/v1/controller/ApiControllerAdvice.java, src/main/java/com/researchspace/service/chemistry/ChemistryClient.java, src/main/java/com/researchspace/service/chemistry/ChemistryClientException.java, src/main/java/com/researchspace/service/impl/StoichiometryServiceImpl.java, src/test/java/com/researchspace/service/chemistry/ChemistryClientTest.java
This change stops the masking of problems from the chemistry service back to the rspace user.
Previously, an error from the chemistry service stoichiometry endpoint would be wrapped in a StoichiometryException with a generic message. Now, we maintain the http status code and message from the chemistry service and let ChemistryClientException bubble up to the stoichiometry controller where it is handled and returned to the client. The common case for this is a user trying to generate a stoichiometry analysis for a non-reaction chemical element.
There are other interactions between `rspace-web` and `chemistry` which could be updated to handle issues better as is done here. There's a ticket on the backlog for that.
1. Run `rspace-web` and the `rsdev-815-error-responses` branch of `chemistry` …
=> Rsdev 815 stoichiometry error messages
