rspace-os/rspace-web

src/main/webapp/ui/src/eln/gallery/components/MainPanel.js
src/main/webapp/ui/src/eln/gallery/components/MoveDialog.js
src/main/webapp/ui/src/eln/gallery/components/TreeView.js
src/main/webapp/ui/src/eln/gallery/index.js
src/main/webapp/ui/src/eln/gallery/useGalleryListing.js

RSDEV-269 Provide sorting of new gallery

---

src/main/java/com/researchspace/service/impl/DocumentTagManagerImpl.java
src/main/java/com/researchspace/webapp/controller/NotebookEditorController.java
src/main/java/com/researchspace/webapp/controller/StructuredDocumentController.java
src/main/webapp/WEB-INF/pages/notebookEditor/notebookEditor.jsp
src/main/webapp/WEB-INF/pages/workspace/editor/structuredDocument.jsp

PRT-640: fix console error about unset ontology variables in revision history view

---

src/main/java/com/researchspace/webapp/controller/StructuredDocumentController.java
src/main/webapp/common/header.jsp
src/main/webapp/scripts/externalTinymcePlugins/googledrive/plugin.min.js
src/main/webapp/scripts/pages/workspace/mediaGalleryManager.js

Reactivates the google drive integration by replacing deprecated google apis. 
This is part 1 of 2 of fully fixing Google Drive, as until our app is authorised by Google there is a user cap of 100 users, which we have maxed out. This _should_ re-activate the integration for any of those 100 users, although we don't know which accounts are part of the 100 users, only that the cap has been reached.

Rsdev 258 reactivate google drive

---

src/main/webapp/ui/src/Inventory/Sample/Content/SubsampleDetails.js

- Image
- Description
- Barcodes

RSDEV-306 Some additional fields for the subsample details panel

---

src/main/java/com/researchspace/webapp/controller/UserProfileController.java
src/main/webapp/ui/src/common/ApiServiceBase.js

This PR fixes a problem with continuous repeated calls to `/inventoryOauthToken` endpoint that can be triggered on document editor page in rare network problem scenarios.

RSDEV-377: timed apitoken requests

---

pom.xml
src/main/java/com/researchspace/api/v1/SubSamplesApi.java
src/main/java/com/researchspace/api/v1/controller/InventoryRecordValidator.java
src/main/java/com/researchspace/api/v1/controller/SampleApiValidator.java
src/main/java/com/researchspace/api/v1/controller/SubSampleApiPostConfigValidator.java
src/main/java/com/researchspace/api/v1/controller/SubSamplesApiController.java
src/main/java/com/researchspace/service/inventory/SubSampleApiManager.java
src/main/java/com/researchspace/service/inventory/impl/InventoryImportManagerImpl.java
src/main/java/com/researchspace/service/inventory/impl/SampleApiManagerImpl.java
src/main/java/com/researchspace/service/inventory/impl/SubSampleApiManagerImpl.java
src/main/java/com/researchspace/service/inventory/impl/SubSampleApiPostConfig.java
src/main/java/com/researchspace/service/inventory/impl/SubSampleCreateNewConfig.java
src/main/webapp/WEB-INF/pages/public/apiDocs.jsp
src/main/webapp/resources/rspace_api_inventory_specs_1_104_0.yaml
src/test/java/com/researchspace/api/v1/controller/SubSamplesApiControllerMVCIT.java
src/test/java/com/researchspace/service/inventory/SubSampleApiManagerTest.java
src/test/java/com/researchspace/testutils/BaseManagerTestCaseBase.java
src/test/java/com/researchspace/webapp/filter/SSOShiroFormAuthFilterTest.java

Adds new `/subSamples` POST endpoint to Inventory API, which can be used to create completely new subsamples within a sample.

RSDEV-314: inventory API endpoint for creating new subsamples

---

src/main/java/com/researchspace/webapp/integrations/dmponline/DMPOnlineController.java
src/main/resources/deployments/defaultDeployment.properties
src/main/resources/deployments/dev/deployment.properties
src/test/java/com/researchspace/webapp/filter/SSOShiroFormAuthFilterTest.java

✅  Successfullt tested on AWS  ✅ 
https://github.com/user-attachments/assets/4a8b66b0-fef5-4a1b-b6e4-f5ed297f3e91

RSDEV-359: Amend test server for DMPonline and fix json request

---

src/main/webapp/ui/src/eln/gallery/components/MainPanel.js

- Background of selected file card has a slight blue colour to make it more obvious which files are selected
- The version number if added to the file card, just like in the old gallery

RSDEV-388 Minor new gallery UI tweaks

---

src/main/webapp/ui/src/eln/gallery/components/MainPanel.js

The panel that was appearing to act as a dropzone for dragging-and-dropping files from outside of the browser and into the new Gallery was not obvious for some absent-mindedly dragging files in. Any drag-and-drop event that concluded outside of the panel was silently ignored and user may not notice that they did in fact not import the files.
Increasing the size of the panel to cover the whole page was not an option as we would lose the ability to drag-and-drop files into a specific folder. Therefore, the background of the card view was instead turned into the dropzone, with a blue outline to indicate this.

RSDEV-391 Remove drag-and-drop panel from new gallery; supporting dropping anywhere instead

---

src/main/webapp/ui/src/eln/gallery/components/AppBar.js
src/main/webapp/ui/src/eln/gallery/components/TreeView.js
src/main/webapp/ui/src/eln/gallery/index.js

- Tapping sidebar should reset search parameters
- Doubling clicking tree view should behave like double click file card

RSDEV-389 Tweaks to new gallery navigation

---

src/main/webapp/ui/src/eln/gallery/components/ActionsMenu.js
src/main/webapp/ui/src/eln/gallery/components/AppBar.js
src/main/webapp/ui/src/eln/gallery/components/Carousel.js
src/main/webapp/ui/src/eln/gallery/components/InfoPanel.js
src/main/webapp/ui/src/eln/gallery/components/MainPanel.js
src/main/webapp/ui/src/eln/gallery/components/Sidebar.js
src/main/webapp/ui/src/eln/gallery/components/TreeView.js
src/main/webapp/ui/src/eln/gallery/components/__tests__/MainPanel.test.js
src/main/webapp/ui/src/eln/gallery/index.js
src/main/webapp/ui/src/eln/gallery/picker/index.js

This change adds
- Role region and label to the
- sidebar
- breadcrumbs
- listing including views: grid, tree, and carousel
- info panel
- aria-attributes to the expandable sections
- sorting
- view
- actions
- sidebar
- mobile info panel

Accessibility tweaks for the new gallery

---

src/main/webapp/ui/src/eln/gallery/components/MainPanel.js
src/main/webapp/ui/src/eln/gallery/components/TreeView.js

This fixes the unfortunate side effect introduced by commit 221c1c8b38

PRT-854 Reinstate the dragging of multiple files in treeview

---

src/main/webapp/ui/src/eln/gallery/components/MainPanel.js

It's very subtle, but the disabled folder is still animating. The animation suggests that it can be used as a dropzone but the opacity suggests that it can't

Don't animate folder that is being moved and can't be a destination

---

src/main/java/com/researchspace/webapp/integrations/github/GitHubController.java
src/main/resources/deployments/dev/deployment.properties
src/main/webapp/WEB-INF/pages/connect/github/connected.jsp
src/main/webapp/scripts/externalTinymcePlugins/github/dialog.htm
src/test/java/com/researchspace/webapp/integrations/github/GitHubControllerMVCIT.java

* when browsing connected github repositories, query for name of default branch rather than assuming it's "master"
* minor refactoring & fixing scrollbar on "Github link" dialog

RSDEV-455: GitHub integration now connects to default branch of the repo

---

src/main/java/com/researchspace/api/v1/controller/FilesApiController.java
src/main/java/com/researchspace/service/RSChemElementManager.java
src/main/java/com/researchspace/service/impl/RSChemElementManagerImpl.java
src/main/java/com/researchspace/webapp/controller/GalleryController.java

refactor method called for newly uploaded chemical file from GalleryController into RSChemElementManager, then call it on file upload through FilesApiController

RSDEV-511: chemical files uploaded through public API should be processed the same way as uploaded through Gallery

---

src/main/java/com/researchspace/service/impl/AsyncDepositorImpl.java
src/main/java/com/researchspace/service/impl/DMPUpdateHandler.java

✅  Successfully tested on AWS instance https://rsdev-527-6.researchspace.com/ (mapped to https://dmponline-test.researchspace.com/) ✅ 
Videos:
1. https://github.com/user-attachments/assets/7a4181bd-3f4f-4def-ae9f-0bd4d6843b02
2. https://github.com/user-attachments/assets/e2101d6a-10a7-42af-9762-334a88c6734b

RSDEV-527: Fix repository export with DMP fails if DMPonline app is enabled

---

src/main/java/com/researchspace/api/v1/controller/FolderApiController.java
src/main/java/com/researchspace/api/v1/service/impl/RecordApiManagerImpl.java
src/main/java/com/researchspace/dao/GroupDao.java
src/main/java/com/researchspace/dao/hibernate/GroupDaoHibernateImpl.java
src/main/java/com/researchspace/service/FolderManager.java
src/main/java/com/researchspace/service/GroupManager.java
src/main/java/com/researchspace/service/SharingHandler.java
src/main/java/com/researchspace/service/impl/FolderManagerImpl.java
src/main/java/com/researchspace/service/impl/GroupManagerImpl.java
src/main/java/com/researchspace/service/impl/RecordManagerImpl.java
src/main/java/com/researchspace/service/impl/SharingHandlerImpl.java
src/main/java/com/researchspace/webapp/controller/StructuredDocumentController.java
src/main/java/com/researchspace/webapp/controller/WorkspaceController.java
src/main/java/com/researchspace/webapp/controller/WorkspacePermissionsDTOBuilder.java
src/main/webapp/WEB-INF/pages/workspace_ajax.jsp
src/main/webapp/scripts/pages/coreEditor.js
src/main/webapp/scripts/pages/workspace.js
src/test/java/com/researchspace/api/v1/controller/FolderApiControllerTest.java
src/test/java/com/researchspace/api/v1/service/RecordApiManagerTest.java
src/test/java/com/researchspace/dao/GroupDaoHibernateTest.java
src/test/java/com/researchspace/service/GroupManagerTest.java
src/test/java/com/researchspace/service/RecordManagerTest.java
src/test/java/com/researchspace/service/SharingHandlerTest.java
src/test/java/com/researchspace/webapp/controller/FolderManagerStub.java
src/test/java/com/researchspace/webapp/controller/SDocControllerMVCIT.java
src/test/java/com/researchspace/webapp/controller/WorkspaceControllerMVCIT.java
src/test/java/com/researchspace/webapp/controller/WorkspaceControllerTest.java

✅  Successfully tested in AWS instance https://rsdev-438-create-doc-shared-folder-35.researchspace.com/ ✅

[RSDEV-438 - RSDEV-579]: Allow direct creation of document/notebook in shared folders from UI and API

---

src/main/java/com/researchspace/webapp/controller/StructuredDocumentController.java
src/main/java/com/researchspace/webapp/controller/WorkspacePermissionsDTOBuilder.java

✅ Successfully tested on AWS instance https://prt-903-fix-create-template-5.researchspace.com/  ✅

PRT-903: Fix createFromTemplate error and reformatting some code

---

pom.xml
src/main/java/com/researchspace/api/v1/controller/InventoryIdentifiersApiController.java
src/main/java/com/researchspace/service/inventory/impl/InventoryIdentifierApiManagerImpl.java
src/main/java/com/researchspace/webapp/integrations/dmptool/DMPToolOAuthController.java

depending from other 2 PRs:
- rda: https://github.com/rspace-os/rda-dmp-common-standard/pull/6
- dmptool-client: https://github.com/rspace-os/dmptool-java-client/pull/8

PRT-911: Fix viewing public DMPTool DMP listing fails

---

src/main/webapp/ui/src/components/useOneDimensionalRovingTabIndex.spec.tsx
src/main/webapp/ui/src/components/useOneDimensionalRovingTabIndex.story.tsx
src/main/webapp/ui/src/components/useOneDimensionalRovingTabIndex.ts

My continued exploration with using playwright component testing to enforce the spec of particular features and their component parts.

Roving tab index playwright test

---

pom.xml
src/main/java/com/researchspace/model/dtos/ShareConfigElement.java
src/main/java/com/researchspace/service/GroupManager.java
src/main/java/com/researchspace/service/SharingHandler.java
src/main/java/com/researchspace/service/impl/GroupManagerImpl.java
src/main/java/com/researchspace/service/impl/SharingHandlerImpl.java
src/main/java/com/researchspace/webapp/controller/WorkspaceController.java
src/main/java/com/researchspace/webapp/controller/cloud/RSCommunityController.java
src/test/java/com/researchspace/api/v1/controller/API_MVC_TestBase.java
src/test/java/com/researchspace/webapp/controller/MVCTestBase.java
src/test/java/com/researchspace/webapp/controller/WorkspaceControllerMVCIT.java

This PR is depending from: https://github.com/rspace-os/rspace-core-model/pull/25
✅  Successfully tested on AWS instance: https://prt-913-fix-permissions-20.researchspace.com/ ✅

PRT-913: Fix info panels when move document into sharedNotebooks

---

src/main/webapp/ui/src/stores/models/__tests__/SampleModel/fetchAdditionalInfo.test.js

Not why this test is just now failing, nor how it ever asserted what it claims to assert -- I can only assume its related to my recent changes to fetchAdditionalInfo
Just waiting to see the build pass

Fix SampleModel's fetchAdditionalInfo test

---

src/main/webapp/ui/src/Inventory/components/ContextMenu/__tests__/CreateDialog.test.js

***REQUIRED***
- ***brief description of the change***
- ***don't repeat too much information that's already included in the jira/github issue***
- ***if the change includes any UI updates, include screenshots or screen recordings if you think it adds value***
***OPTIONAL***
- ***if there were any particular design decisions made, list them here***
***OPTIONAL***
- ***if there are any particular pre-requisites or instructions for manual testing, list them here***

PRT-938 Fix CreateDialog jest tests

---

Jenkinsfile

In feature branch builds, only run the jest and playwright component tests that could actually be impacted by the changes since the branch diverged from `main`.

Only run changed since js tests

---

src/main/webapp/ui/src/eln/gallery/index.tsx

This change corrects an accessibility issue with the new gallery: [from the WCAG 2.2 spec](https://www.w3.org/TR/WCAG22/#page-titled):
“[Web pages](https://www.w3.org/TR/WCAG22/#dfn-web-page-s) have titles that describe topic or purpose.”
Which is to say, as the user navigates around, the page’s title needs to update to accurately describe the current content such that if the user had multiple tabs open they would be able to figure out which one to go back to.

RSDEV-720 Dynamically update Gallery's title

---

src/main/webapp/scripts/pages/workspace/crudops.js
src/main/webapp/ui/src/Toolbar/Workspace/RenameDialog.tsx
src/main/webapp/ui/src/Toolbar/Workspace/Toolbar.js

This is a small step in the process of migrating the workspace to react. The design of this dialog mimics the Gallery's rename dialog.

RSDEV-677 Migrate workspace rename dialog to react

---

src/main/webapp/ui/src/Inventory/Import/Fields/TemplateDetails.tsx
src/main/webapp/ui/src/Inventory/Sample/Fields/Template/Template.tsx
src/main/webapp/ui/src/Inventory/Search/components/CustomTableHead.tsx
src/main/webapp/ui/src/Inventory/Search/components/ResultRow.tsx
src/main/webapp/ui/src/Inventory/components/Picker/Picker.tsx
src/main/webapp/ui/src/Inventory/components/Picker/TemplatePicker.tsx
src/main/webapp/ui/src/stores/models/SampleModel.tsx
src/main/webapp/ui/src/stores/models/Search.ts

This change just makes a few visual tweaks to make creating samples more intuitive by simplify the step of selecting a template

RSDEV-674 Make template selection clearer

---

pom.xml
src/main/java/com/researchspace/integrations/galaxy/service/GalaxyInvocationDetails.java
src/main/java/com/researchspace/integrations/galaxy/service/GalaxyService.java
src/main/java/com/researchspace/integrations/galaxy/service/GalaxySummaryStatusReport.java
src/main/webapp/ui/src/eln/eln-external-workflows/ExternalWorkflowInvocations.tsx
src/main/webapp/ui/src/eln/eln-external-workflows/__tests__/ExternalWorkFlowsDialog.test.tsx
src/main/webapp/ui/src/eln/eln-external-workflows/index.tsx
src/main/webapp/ui/src/tinyMCE/galaxy/__tests__/Galaxy.test.tsx
src/test/java/com/researchspace/integrations/galaxy/service/ExternalWorkFlowTestMother.java
src/test/java/com/researchspace/integrations/galaxy/service/GalaxyInvocationDetailsTestMother.java
src/test/java/com/researchspace/integrations/galaxy/service/GalaxyServiceTest.java
src/test/java/com/researchspace/integrations/galaxy/service/GalaxySummaryStatusReportTest.java

***REQUIRED***
- ***brief description of the change***
- ***don't repeat too much information that's already included in the jira/github issue***
- ***if the change includes any UI updates, include screenshots or screen recordings if you think it adds value***
***OPTIONAL***
- ***if there were any particular design decisions made, list them here***
***OPTIONAL***
- ***if there are any particular pre-requisites or instructions for manual testing, list them here***

Rsdev 639 galaxy apps page UI

---

src/main/webapp/ui/src/assets/DocLinks.ts

***REQUIRED***
- ***brief description of the change***
- ***don't repeat too much information that's already included in the jira/github issue***
- ***if the change includes any UI updates, include screenshots or screen recordings if you think it adds value***
***OPTIONAL***
- ***if there were any particular design decisions made, list them here***
***OPTIONAL***
- ***if there are any particular pre-requisites or instructions for manual testing, list them here***

PRT-976: link to galaxy helpdocs

---

Jenkinsfile

No wonder I was confused about feature brach building -- it was never getting triggered by my changes.

Include TypeScript files in triggering building feature branch

---

src/test/java/com/researchspace/webapp/integrations/fieldmark/FieldmarkRealConnectionMVCIT.java

Re-ignore the Fieldmark real connection test that was enabled by mistake

Ignore the Real connection test Fieldmark (revert)

---

src/main/webapp/scripts/externalTinymcePlugins/protocols_io/js/main.js
src/main/webapp/scripts/pages/notebookEditor.js
src/main/webapp/scripts/pages/workspace.js

This PR fixes an issue that prevented the user to create a document iun the root workspace

RSDEV-765: Amend JS for the root workspace folder

---

src/main/webapp/ui/package-lock.json
src/main/webapp/ui/package.json

Adds missing `@types/react` and `@types/react-dom` dev dependencies.

fix: add missing React and React DOM typings

---

src/main/java/com/researchspace/webapp/controller/WorkspaceController.java

Previously, the code was showing the error popup if the folder was shared, but its ACL was only permitting one entity (assumed to be a folder owner) to see it. But turns out that shared folders created within a project group do have only one permitted entity, and that is the project group. This is the correct case, and the warning should not be shown.

RSDEV-835: correct logic for showing popup about folder permission problem
